# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/btjogr/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/btjogr/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/btjogr/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_color_block_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_defeated_reg_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_dir_block_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_x_block_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_y_block_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c3_t1_basic_alien_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c4_b2_shield_rst_fsm_fsm.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c5_b1_serial_tx_fsm_fsm.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/alien_game/alien_game_lib/hdl/c5_b2_gamma_fsm_fsm.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/pre_made/hdl/disp_reg_bank.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/pre_made/hdl/disp_serial_led_cannon.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/pre_made/hdl/display_controller_struct.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/pre_made/hdl/en_wr_rtl.vhd}
  {//ad.tuni.fi/home/btjogr/StudentDocuments/Documents/digita design/20/pre_made/hdl/hello_alien_struct.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top HELLO_ALIEN -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef HELLO_ALIEN.dcp

catch { report_utilization -file HELLO_ALIEN_utilization_synth.rpt -pb HELLO_ALIEN_utilization_synth.pb }
