-- VHDL Entity alien_game_lib.c1_b2_half_subtractor.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 09:49:04 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_b2_half_subtractor IS
   PORT( 
      A      : IN     std_logic;
      B      : IN     std_logic;
      borrow : OUT    std_logic;
      diff   : OUT    std_logic
   );

-- Declarations

END c1_b2_half_subtractor ;

--
-- VHDL Architecture alien_game_lib.c1_b2_half_subtractor.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 09:55:13 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_b2_half_subtractor IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   borrow <= dout AND B;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inv'
   dout <= NOT(A);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   diff <= A XOR B;

   -- Instance port mappings.

END struct;
