-- VHDL Entity alien_game_lib.c1_b2_decrementer.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 09:58:24 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_b2_decrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_b2_decrementer ;

--
-- VHDL Architecture alien_game_lib.c1_b2_decrementer.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 13:28:19 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c1_b2_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL borrow  : std_logic;
   SIGNAL borrow1 : std_logic;
   SIGNAL borrow2 : std_logic;
   SIGNAL dout    : std_logic;


   -- Component Declarations
   COMPONENT c1_b2_half_subtractor
   PORT (
      A      : IN     std_logic ;
      B      : IN     std_logic ;
      borrow : OUT    std_logic ;
      diff   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_b2_half_subtractor USE ENTITY alien_game_lib.c1_b2_half_subtractor;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= '1';

   -- Instance port mappings.
   U_0 : c1_b2_half_subtractor
      PORT MAP (
         A      => value(0),
         B      => dout,
         borrow => borrow,
         diff   => result(0)
      );
   U_1 : c1_b2_half_subtractor
      PORT MAP (
         A      => value(1),
         B      => borrow,
         borrow => borrow1,
         diff   => result(1)
      );
   U_2 : c1_b2_half_subtractor
      PORT MAP (
         A      => value(2),
         B      => borrow1,
         borrow => borrow2,
         diff   => result(2)
      );

END struct;
