-- VHDL Entity alien_game_lib.c2_t1_pixel_io.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 15:58:07 22.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_pixel_io IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_pixel_io ;

--
-- VHDL Architecture alien_game_lib.c2_t1_pixel_io.struct
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 15:58:07 22.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_pixel_io IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(15 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(15 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'split'
   SIGNAL mw_U_4temp_din : std_logic_vector(15 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout <= 0x0101FF0000;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout <= 0x03030000FF;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(dout, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => dout1 <= dout;
      WHEN '1' => dout1 <= dout;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'split'
   mw_U_4temp_din <= dout1;
   u_4combo_proc: PROCESS (mw_U_4temp_din)
   VARIABLE temp_din: std_logic_vector(39 DOWNTO 0);
   BEGIN
      temp_din := (OTHERS => 'X');
      temp_din(15 DOWNTO 0) := mw_U_4temp_din;
      x_coord <= temp_din(7 DOWNTO 0);
      y_coord <= temp_din(15 DOWNTO 8);
      color_BGR <= temp_din(39 DOWNTO 16);
   END PROCESS u_4combo_proc;

   -- Instance port mappings.

END struct;
