-- VHDL Entity alien_game_lib.c2_t1_pixel_io.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 15:28:46 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_pixel_io IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_pixel_io ;

--
-- VHDL Architecture alien_game_lib.c2_t1_pixel_io.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 15:28:46 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_pixel_io IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout2 <= "00100000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout1 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   color_BGR <= "111111110000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   y_coord <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(dout1, dout2, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => x_coord <= dout1;
      WHEN '1' => x_coord <= dout2;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- Instance port mappings.

END struct;
