-- VHDL Entity alien_game_lib.c2_t1_pixel_conf.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 14:11:09 22.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_pixel_conf IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_pixel_conf ;

--
-- VHDL Architecture alien_game_lib.c2_t1_pixel_conf.struct
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 14:11:08 22.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_pixel_conf IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   x_coord <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   y_coord <= "11101000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   color_BGR <= x"FF0000";

   -- Instance port mappings.

END struct;
