-- VHDL Entity alien_game_lib.c2_t1_combined_pixel.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:32:55 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_combined_pixel IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw        : IN     std_logic;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_combined_pixel ;

--
-- VHDL Architecture alien_game_lib.c2_t1_combined_pixel.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:32:52 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t1_combined_pixel IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color_BGR1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL color_BGR2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL x_coord1   : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_coord2   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord1   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord2   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t1_pixel_conf
   PORT (
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t1_pixel_io
   PORT (
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t1_pixel_conf USE ENTITY alien_game_lib.c2_t1_pixel_conf;
   FOR ALL : c2_t1_pixel_io USE ENTITY alien_game_lib.c2_t1_pixel_io;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(color_BGR1, color_BGR2, sw)
   BEGIN
      CASE sw IS
      WHEN '0' => color_BGR <= color_BGR1;
      WHEN '1' => color_BGR <= color_BGR2;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(x_coord1, x_coord2, sw)
   BEGIN
      CASE sw IS
      WHEN '0' => x_coord <= x_coord1;
      WHEN '1' => x_coord <= x_coord2;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(y_coord1, y_coord2, sw)
   BEGIN
      CASE sw IS
      WHEN '0' => y_coord <= y_coord1;
      WHEN '1' => y_coord <= y_coord2;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_0 : c2_t1_pixel_conf
      PORT MAP (
         color_BGR => color_BGR1,
         x_coord   => x_coord1,
         y_coord   => y_coord1
      );
   U_1 : c2_t1_pixel_io
      PORT MAP (
         btn       => btn,
         color_BGR => color_BGR2,
         x_coord   => x_coord2,
         y_coord   => y_coord2
      );

END struct;
