-- VHDL Entity alien_game_lib.c2_t1_pixel_io.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:12:52 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_pixel_io IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_pixel_io ;

--
-- VHDL Architecture alien_game_lib.c2_t1_pixel_io.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 13:23:43 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_pixel_io IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL din4 : std_logic_vector(23 DOWNTO 0);
   SIGNAL din5 : std_logic_vector(23 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   din0 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   din1 <= "00000010";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   din2 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   din3 <= "00000010";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   din4 <= "111111110000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din5 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(din0, din1, btn)
   BEGIN
      CASE btn(3) IS
      WHEN '0' => x_coord <= din0;
      WHEN '1' => x_coord <= din1;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(din2, din3, btn)
   BEGIN
      CASE btn(2) IS
      WHEN '0' => y_coord <= din2;
      WHEN '1' => y_coord <= din3;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(din4, din5, btn)
   BEGIN
      CASE btn(1) IS
      WHEN '0' => color_BGR <= din4;
      WHEN '1' => color_BGR <= din5;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
