-- VHDL Entity alien_game_lib.c3_t1_dir_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:17:05 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_dir_block IS
   PORT( 
      X_q    : IN     std_logic_vector (7 DOWNTO 0);
      clk    : IN     std_logic;
      enable : IN     std_logic;
      rst_n  : IN     std_logic;
      dir_q  : OUT    std_logic
   );

-- Declarations

END c3_t1_dir_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_dir_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:28:58 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_dir_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0  : std_logic;
   SIGNAL din1  : std_logic;
   SIGNAL din2  : std_logic;
   SIGNAL din3  : std_logic;
   SIGNAL dir_d : std_logic;
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL fout  : std_logic;
   SIGNAL fout1 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL dir_q_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   dir_q_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dir_d;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   din0 <= din3 AND fout;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   din1 <= dir_q_internal AND fout1;

   -- ModuleWare code(v1.12) for instance 'need_flip' of 'and'
   dout3 <= din2 AND enable;

   -- ModuleWare code(v1.12) for instance 'at_left_edge' of 'comp'
   at_left_edgecombo_proc : PROCESS (dout, X_q)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(dout) = unsigned(X_q)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS at_left_edgecombo_proc;

   -- ModuleWare code(v1.12) for instance 'at_right_edge' of 'comp'
   at_right_edgecombo_proc : PROCESS (X_q, dout1)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(X_q) = unsigned(dout1)) THEN
         temp_lout := '1';
      END IF;
   fout1 <= temp_lout;
   END PROCESS at_right_edgecombo_proc;

   -- ModuleWare code(v1.12) for instance 'X_left_edge' of 'constval'
   dout <= "00000001";

   -- ModuleWare code(v1.12) for instance 'X_right_edge' of 'constval'
   dout1 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'inv'
   din3 <= NOT(dir_q_internal);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(dir_q_internal, din3, dout3)
   BEGIN
      CASE dout3 IS
      WHEN '0' => dir_d <= dir_q_internal;
      WHEN '1' => dir_d <= din3;
      WHEN OTHERS => dir_d <= 'X';
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'at_edge' of 'or'
   din2 <= din0 OR din1;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   dir_q <= dir_q_internal;

END struct;
