-- VHDL Entity alien_game_lib.c3_t1_x_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:52:09 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_x_block IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      dir_q          : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      alien_x        : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_x_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_x_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 12:55:02 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_x_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL X_en   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_hit  : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_ls   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_q    : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_rs   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_step : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1   : std_logic_vector(7 DOWNTO 0);
   SIGNAL shift  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   X_q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000001";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= X_q;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   shift <= '1';

   -- ModuleWare code(v1.12) for instance 'X_ZERO' of 'constval'
   din1 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'lshift'
   u_1combo_proc : PROCESS (X_q, shift)
   VARIABLE temp_shift : std_logic_vector (0 DOWNTO 0);
   VARIABLE temp_dout : std_logic_vector (7 DOWNTO 0);
   VARIABLE temp_din : std_logic_vector (7 DOWNTO 0);
   BEGIN
      temp_shift(0) := shift;
      temp_din := X_q;
      FOR i IN 0 TO 0 LOOP
         IF (temp_shift(i) = '1') THEN
            temp_dout := (OTHERS => '0');
            temp_dout(7 DOWNTO 2**i) := temp_din(7 - 2**i DOWNTO 0);
         ELSIF (temp_shift(i) = '0') THEN
            temp_dout := temp_din;
         ELSE
            temp_dout := (OTHERS => 'X');
         END IF;
         temp_din := temp_dout;
      END LOOP;
      X_ls <= temp_dout;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(X_ls, X_rs, dir_q)
   BEGIN
      CASE dir_q IS
      WHEN '0' => X_step <= X_ls;
      WHEN '1' => X_step <= X_rs;
      WHEN OTHERS => X_step <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'defeated_ctrl' of 'mux'
   defeated_ctrlcombo_proc: PROCESS(X_hit, din1, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => alien_x <= X_hit;
      WHEN '1' => alien_x <= din1;
      WHEN OTHERS => alien_x <= (OTHERS => 'X');
      END CASE;
   END PROCESS defeated_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'enable_ctrl' of 'mux'
   enable_ctrlcombo_proc: PROCESS(X_q, X_step, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => X_en <= X_q;
      WHEN '1' => X_en <= X_step;
      WHEN OTHERS => X_en <= (OTHERS => 'X');
      END CASE;
   END PROCESS enable_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'hit_ctrl' of 'mux'
   hit_ctrlcombo_proc: PROCESS(X_en, din1, hit)
   BEGIN
      CASE hit IS
      WHEN '0' => X_hit <= X_en;
      WHEN '1' => X_hit <= din1;
      WHEN OTHERS => X_hit <= (OTHERS => 'X');
      END CASE;
   END PROCESS hit_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'rshift'
   u_2combo_proc : PROCESS (X_q, shift)
   VARIABLE temp_shift : std_logic_vector (0 DOWNTO 0);
   VARIABLE temp_dout : std_logic_vector (7 DOWNTO 0);
   VARIABLE temp_din : std_logic_vector (7 DOWNTO 0);
   BEGIN
      temp_shift(0) := shift;
      temp_din := X_q;
      FOR i IN 0 TO 0 LOOP
         IF (temp_shift(i) = '1') THEN
            temp_dout := (OTHERS => '0');
            temp_dout(7 - 2**i DOWNTO 0) := temp_din(7 DOWNTO 2**i);
         ELSIF (temp_shift(i) = '0') THEN
            temp_dout := temp_din;
         ELSE
            temp_dout := (OTHERS => 'X');
         END IF;
         temp_din := temp_dout;
      END LOOP;
      X_rs <= temp_dout;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
