-- VHDL Entity alien_game_lib.c3_t1_y_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 17:57:46 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_y_block IS
   PORT( 
      alien_defeated : IN     std_logic;
      hit            : IN     std_logic;
      Y              : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_y_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_y_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 17:57:46 26.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_y_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL sel   : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'Y_TOP' of 'constval'
   dout <= "00000001";

   -- ModuleWare code(v1.12) for instance 'Y_ZERO' of 'constval'
   dout1 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout, dout1, sel)
   BEGIN
      CASE sel IS
      WHEN '0' => Y <= dout;
      WHEN '1' => Y <= dout1;
      WHEN OTHERS => Y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   sel <= hit OR alien_defeated;

   -- Instance port mappings.

END struct;
