-- VHDL Entity alien_game_lib.c3_t1_basic_alien.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:37:16  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_basic_alien IS
   PORT( 
      clk         : IN     std_logic;
      enable      : IN     std_logic;
      hit         : IN     std_logic;
      rst_n       : IN     std_logic;
      alien_color : OUT    std_logic_vector (23 DOWNTO 0);
      alien_x     : OUT    std_logic_vector (7 DOWNTO 0);
      alien_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_basic_alien ;

--
-- VHDL Architecture alien_game_lib.c3_t1_basic_alien.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:37:16  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t1_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_defeated : std_logic;
   SIGNAL dir_q          : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL alien_x_internal : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c3_t1_color_block
   PORT (
      alien_defeated : IN     std_logic ;
      hit            : IN     std_logic ;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t1_defeated_reg
   PORT (
      clk            : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      alien_defeated : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c3_t1_dir_block
   PORT (
      X_q   : IN     std_logic_vector (7 DOWNTO 0);
      clk   : IN     std_logic ;
      rst_n : IN     std_logic ;
      dir_q : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c3_t1_x_block
   PORT (
      alien_defeated : IN     std_logic ;
      clk            : IN     std_logic ;
      dir_q          : IN     std_logic ;
      enable         : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      alien_x        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c3_t1_y_block
   PORT (
      alien_defeated : IN     std_logic ;
      hit            : IN     std_logic ;
      alien_y        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_color_block USE ENTITY alien_game_lib.c3_t1_color_block;
   FOR ALL : c3_t1_defeated_reg USE ENTITY alien_game_lib.c3_t1_defeated_reg;
   FOR ALL : c3_t1_dir_block USE ENTITY alien_game_lib.c3_t1_dir_block;
   FOR ALL : c3_t1_x_block USE ENTITY alien_game_lib.c3_t1_x_block;
   FOR ALL : c3_t1_y_block USE ENTITY alien_game_lib.c3_t1_y_block;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_2 : c3_t1_color_block
      PORT MAP (
         alien_defeated => alien_defeated,
         hit            => hit,
         alien_color    => alien_color
      );
   U_3 : c3_t1_defeated_reg
      PORT MAP (
         clk            => clk,
         hit            => hit,
         rst_n          => rst_n,
         alien_defeated => alien_defeated
      );
   U_4 : c3_t1_dir_block
      PORT MAP (
         X_q   => alien_x_internal,
         clk   => clk,
         rst_n => rst_n,
         dir_q => dir_q
      );
   U_0 : c3_t1_x_block
      PORT MAP (
         alien_defeated => alien_defeated,
         clk            => clk,
         dir_q          => dir_q,
         enable         => enable,
         hit            => hit,
         rst_n          => rst_n,
         alien_x        => alien_x_internal
      );
   U_1 : c3_t1_y_block
      PORT MAP (
         alien_defeated => alien_defeated,
         hit            => hit,
         alien_y        => alien_y
      );

   -- Implicit buffered output assignments
   alien_x <= alien_x_internal;

END struct;
