-- VHDL Entity alien_game_lib.c3_t1_defeated_reg.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:42:45 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_defeated_reg IS
   PORT( 
      clk            : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      alien_defeated : OUT    std_logic
   );

-- Declarations

END c3_t1_defeated_reg ;

--
-- VHDL Architecture alien_game_lib.c3_t1_defeated_reg.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:42:45 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_defeated_reg IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL def_d : std_logic;
   SIGNAL def_q : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   def_q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= def_d;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   def_d <= def_q OR hit;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'pbuf'
   u_2seq_proc: PROCESS (def_q)
   BEGIN
      IF (def_q ='1' ) THEN
         alien_defeated <= '1';
      ELSIF (def_q ='H' ) THEN
         alien_defeated <= '1';
      ELSIF (def_q ='0' ) THEN
         alien_defeated <= '0';
      ELSIF (def_q ='L' ) THEN
         alien_defeated <= '0';
      ELSIF (def_q ='U' ) THEN
         alien_defeated <= 'U';
      ELSIF (def_q ='X' ) THEN
         alien_defeated <= 'X';
      ELSIF (def_q ='Z' ) THEN
         alien_defeated <= 'X';
      END IF;
   END PROCESS u_2seq_proc;

   -- Instance port mappings.

END struct;
