-- VHDL Entity alien_game_lib.c3_t1_color_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-308-SPC)
--          at - 12:07:49 16.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_color_block IS
   PORT( 
      alien_defeated : IN     std_logic;
      hit            : IN     std_logic;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c3_t1_color_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_color_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-308-SPC)
--          at - 12:07:49 16.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_color_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL sel   : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'C_NORM' of 'constval'
   dout1 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'C_ZERO' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout1, dout, sel)
   BEGIN
      CASE sel IS
      WHEN '0' => alien_color <= dout1;
      WHEN '1' => alien_color <= dout;
      WHEN OTHERS => alien_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'dead_now' of 'or'
   sel <= hit OR alien_defeated;

   -- Instance port mappings.

END struct;
