-- VHDL Entity alien_game_lib.c3_t1_alien_color.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:43:48  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_alien_color IS
   PORT( 
      alien_defeated : IN     std_logic;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c3_t1_alien_color ;

--
-- VHDL Architecture alien_game_lib.c3_t1_alien_color.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:43:48  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_alien_color IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'C_NORM' of 'constval'
   dout1 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'C_ZERO' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout1, dout, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => alien_color <= dout1;
      WHEN '1' => alien_color <= dout;
      WHEN OTHERS => alien_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
