-- VHDL Entity alien_game_lib.c3_t1_dir_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:06:16  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_dir_block IS
   PORT( 
      X_q   : IN     std_logic_vector (7 DOWNTO 0);
      clk   : IN     std_logic;
      rst_n : IN     std_logic;
      dir_q : OUT    std_logic
   );

-- Declarations

END c3_t1_dir_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_dir_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:46:33 24.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_dir_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL at_edge       : std_logic;
   SIGNAL at_left_egde  : std_logic;
   SIGNAL at_right_edge : std_logic;
   SIGNAL din0          : std_logic;
   SIGNAL din1          : std_logic;
   SIGNAL dir_d         : std_logic;
   SIGNAL dir_inv       : std_logic;
   SIGNAL dout          : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1         : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL dir_q_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   dir_q_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dir_d;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   din0 <= dir_q_internal AND at_left_egde;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and'
   din1 <= dir_inv AND at_right_edge;

   -- ModuleWare code(v1.12) for instance 'at_left_edge' of 'comp'
   at_left_edgecombo_proc : PROCESS (dout, X_q)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(dout) = unsigned(X_q)) THEN
         temp_lout := '1';
      END IF;
   at_left_egde <= temp_lout;
   END PROCESS at_left_edgecombo_proc;

   -- ModuleWare code(v1.12) for instance 'at_right_edge' of 'comp'
   at_right_edgecombo_proc : PROCESS (X_q, dout1)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(X_q) = unsigned(dout1)) THEN
         temp_lout := '1';
      END IF;
   at_right_edge <= temp_lout;
   END PROCESS at_right_edgecombo_proc;

   -- ModuleWare code(v1.12) for instance 'X_left_edge' of 'constval'
   dout <= "00000001";

   -- ModuleWare code(v1.12) for instance 'X_right_edge' of 'constval'
   dout1 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'inv'
   dir_inv <= NOT(dir_q_internal);

   -- ModuleWare code(v1.12) for instance 'at_edge' of 'or'
   at_edge <= din0 OR din1;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'xor'
   dir_d <= at_edge XOR dir_q_internal;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   dir_q <= dir_q_internal;

END struct;
