-- VHDL Entity alien_game_lib.c3_t1_x_block.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:31:53 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_x_block IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      dir_q          : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      X_d            : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_x_block ;

--
-- VHDL Architecture alien_game_lib.c3_t1_x_block.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:38:20 28.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c3_t1_x_block IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL X_en   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_hit  : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_ls   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_q    : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_rs   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_step : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1   : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL X_d_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   X_q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000001";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= X_d_internal;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'X_ZERO' of 'constval'
   din1 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'lshift'

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(X_ls, X_rs, dir_q)
   BEGIN
      CASE dir_q IS
      WHEN '0' => X_step <= X_ls;
      WHEN '1' => X_step <= X_rs;
      WHEN OTHERS => X_step <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'defeated_ctrl' of 'mux'
   defeated_ctrlcombo_proc: PROCESS(X_hit, din1, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => X_d_internal <= X_hit;
      WHEN '1' => X_d_internal <= din1;
      WHEN OTHERS => X_d_internal <= (OTHERS => 'X');
      END CASE;
   END PROCESS defeated_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'enable_ctrl' of 'mux'
   enable_ctrlcombo_proc: PROCESS(X_q, X_step, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => X_en <= X_q;
      WHEN '1' => X_en <= X_step;
      WHEN OTHERS => X_en <= (OTHERS => 'X');
      END CASE;
   END PROCESS enable_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'hit_ctrl' of 'mux'
   hit_ctrlcombo_proc: PROCESS(X_en, din1, hit)
   BEGIN
      CASE hit IS
      WHEN '0' => X_hit <= X_en;
      WHEN '1' => X_hit <= din1;
      WHEN OTHERS => X_hit <= (OTHERS => 'X');
      END CASE;
   END PROCESS hit_ctrlcombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'rshift'

   -- Instance port mappings.

   -- Implicit buffered output assignments
   X_d <= X_d_internal;

END struct;
