-- VHDL Entity alien_game_lib.c4_b1_bullet_fsm.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-308-SPC)
--          at - 10:16:03 11.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_b1_bullet_fsm IS
   PORT( 
      btn_0    : IN     std_logic;
      clk      : IN     std_logic;
      enable   : IN     std_logic;
      gun_x    : IN     std_logic_vector (7 DOWNTO 0);
      rst      : IN     std_logic;
      bullet_x : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y : OUT    std_logic_vector (7 DOWNTO 0);
      color    : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c4_b1_bullet_fsm ;

--
-- VHDL Architecture alien_game_lib.c4_b1_bullet_fsm.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-308-SPC)
--          at - 12:32:26 11.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c4_b1_bullet_fsm IS

   -- Architecture Declarations
   SIGNAL bullet_x_reg : std_logic_vector(7 DOWNTO 0);  
   SIGNAL bullet_y_reg : std_logic_vector(7 DOWNTO 0);  

   TYPE STATE_TYPE IS (
      IDLE,
      FIRE,
      FLY
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= IDLE;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;

         -- Combined Actions
         CASE current_state IS
            WHEN IDLE => 
               bullet_x_reg <= "00000000" ;
               bullet_y_reg <= "00000000" ;
            WHEN FIRE => 
               IF (TRUE) THEN 
                  bullet_x_reg <= gun_x;
                  bullet_y_reg <= "00100000";
               END IF;
            WHEN FLY => 
               IF (enable = '1' AND bullet_y_reg(0) = '0') THEN 
                  bullet_y_reg <= ( '0' & bullet_y_reg(7 downto 1) ) ;
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      btn_0,
      bullet_y_reg,
      current_state,
      enable
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN IDLE => 
            IF (btn_0 = '1') THEN 
               next_state <= FIRE;
            ELSE
               next_state <= IDLE;
            END IF;
         WHEN FIRE => 
            IF (TRUE) THEN 
               next_state <= FLY;
            ELSE
               next_state <= FIRE;
            END IF;
         WHEN FLY => 
            IF (enable = '1' AND bullet_y_reg(0) = '0') THEN 
               next_state <= FLY;
            ELSIF (enable = '1' AND bullet_y_reg(0) = '1') THEN 
               next_state <= IDLE;
            ELSE
               next_state <= FLY;
            END IF;
         WHEN OTHERS =>
            next_state <= IDLE;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   -- Default Assignment
   color <= x"FF0000";
 
   -- Concurrent Statements
   bullet_x <= bullet_x_reg;
   bullet_y <= bullet_y_reg;
END fsm;
