-- VHDL Entity alien_game_lib.c4_b2_shield_rst_fsm.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-319-SPC)
--          at - 11:40:01  9.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_b2_shield_rst_fsm IS
   PORT( 
      clk   : IN     std_logic;
      rst_n : IN     std_logic;
      done  : OUT    std_logic;
      s_rst : OUT    std_logic
   );

-- Declarations

END c4_b2_shield_rst_fsm ;

--
-- VHDL Architecture alien_game_lib.c4_b2_shield_rst_fsm.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 12:41:51  9.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c4_b2_shield_rst_fsm IS

   TYPE STATE_TYPE IS (
      IDLE,
      RST_LOW_0,
      RST_HIGH,
      RST_DONE,
      RST_LOW_1,
      RST_LOW_2,
      RST_LOW_3,
      RST_LOW_4,
      WAIT_AFTER_RST
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= IDLE;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN IDLE => 
            IF (rst_n = '1') THEN 
               next_state <= RST_LOW_0;
            ELSE
               next_state <= IDLE;
            END IF;
         WHEN RST_LOW_0 => 
            IF (TRUE) THEN 
               next_state <= RST_LOW_1;
            ELSE
               next_state <= RST_LOW_0;
            END IF;
         WHEN RST_HIGH => 
            IF (TRUE) THEN 
               next_state <= WAIT_AFTER_RST;
            ELSE
               next_state <= RST_HIGH;
            END IF;
         WHEN RST_DONE => 
            IF (rst_n = '1') THEN 
               next_state <= RST_DONE;
            ELSIF (rst_n = '0') THEN 
               next_state <= IDLE;
            ELSE
               next_state <= RST_DONE;
            END IF;
         WHEN RST_LOW_1 => 
            IF (TRUE) THEN 
               next_state <= RST_LOW_2;
            ELSE
               next_state <= RST_LOW_1;
            END IF;
         WHEN RST_LOW_2 => 
            IF (TRUE) THEN 
               next_state <= RST_LOW_3;
            ELSE
               next_state <= RST_LOW_2;
            END IF;
         WHEN RST_LOW_3 => 
            IF (TRUE) THEN 
               next_state <= RST_LOW_4;
            ELSE
               next_state <= RST_LOW_3;
            END IF;
         WHEN RST_LOW_4 => 
            IF (TRUE) THEN 
               next_state <= RST_HIGH;
            ELSE
               next_state <= RST_LOW_4;
            END IF;
         WHEN WAIT_AFTER_RST => 
            IF (TRUE) THEN 
               next_state <= RST_DONE;
            ELSE
               next_state <= WAIT_AFTER_RST;
            END IF;
         WHEN OTHERS =>
            next_state <= IDLE;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      done <= '0';
      s_rst <= '1';

      -- Combined Actions
      CASE current_state IS
         WHEN IDLE => 
            s_rst <= '1' ;
            done <= '0' ;
         WHEN RST_LOW_0 => 
            s_rst <= '0' ;
            done <= '0' ;
         WHEN RST_HIGH => 
            s_rst <= '1' ;
            done <= '0' ;
         WHEN RST_DONE => 
            s_rst <= '1' ;
            done <=  '1' ;
         WHEN RST_LOW_1 => 
            s_rst <= '0' ;
            done <= '0' ;
         WHEN RST_LOW_2 => 
            s_rst <= '0' ;
            done <= '0' ;
         WHEN RST_LOW_3 => 
            s_rst <= '0' ;
            done <= '0' ;
         WHEN RST_LOW_4 => 
            s_rst <= '0' ;
            done <= '0' ;
         WHEN WAIT_AFTER_RST => 
            s_rst <= '1' ;
            done <= '0' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
