-- VHDL Entity alien_game_lib.c4_b1_bullet.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:34:53  4.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_b1_bullet IS
   PORT( 
      Gun_x_coord    : IN     std_logic_vector (7 DOWNTO 0);
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      rst_n          : IN     std_logic;
      bullet_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : OUT    std_logic_vector (7 DOWNTO 0);
      color          : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c4_b1_bullet ;

--
-- VHDL Architecture alien_game_lib.c4_b1_bullet.struct
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:34:53  4.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_b1_bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din  : std_logic_vector(7 DOWNTO 0);
   SIGNAL load : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL bullet_y_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   SIGNAL mw_U_4reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'fixshift'
   SIGNAL mw_U_7temp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   din <= mw_U_4reg_cval;
   u_4seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '1') THEN
         mw_U_4reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (load = '1') THEN
            mw_U_4reg_cval <= bullet_y_coord_internal;
         END IF;
      END IF;
   END PROCESS u_4seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and1'
   load <= enable AND btn(0);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'buff'
   bullet_x_coord <= Gun_x_coord;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   color <= "111111110000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'fixshift'
   bullet_y_coord_internal <= mw_U_7temp_dout;
   u_7combo_proc: PROCESS (din)
   BEGIN
      mw_U_7temp_dout <= (OTHERS => '0');
      mw_U_7temp_dout(6 DOWNTO 0) <= din(7 + 0 DOWNTO 1 + 0);
   END PROCESS u_7combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   bullet_y_coord <= bullet_y_coord_internal;

END struct;
