-- VHDL Entity alien_game_lib.c4_t1_top_gun.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:35:14  4.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_top_gun IS
   PORT( 
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic;
      enable     : IN     std_logic;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic;
      gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      gun_x      : OUT    std_logic_vector (7 DOWNTO 0);
      gun_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_top_gun ;

--
-- VHDL Architecture alien_game_lib.c4_t1_top_gun.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 10:35:10  4.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_top_gun IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL gun_x_q : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c4_t1_gun_ctrl
   PORT (
      btn     : IN     std_logic_vector (3 DOWNTO 0);
      clk     : IN     std_logic ;
      enable  : IN     std_logic ;
      rst_n   : IN     std_logic ;
      gun_x_q : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_gun_pixel_mapper
   PORT (
      gun_px_idx     : IN     std_logic_vector (1 DOWNTO 0);
      gun_x_center_q : IN     std_logic_vector (7 DOWNTO 0);
      gun_color      : OUT    std_logic_vector (23 DOWNTO 0);
      gun_idx_x      : OUT    std_logic_vector (7 DOWNTO 0);
      gun_idx_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_gun_ctrl USE ENTITY alien_game_lib.c4_t1_gun_ctrl;
   FOR ALL : c4_t1_gun_pixel_mapper USE ENTITY alien_game_lib.c4_t1_gun_pixel_mapper;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : c4_t1_gun_ctrl
      PORT MAP (
         btn     => btn,
         clk     => clk,
         enable  => enable,
         rst_n   => rst_n,
         gun_x_q => gun_x_q
      );
   U_1 : c4_t1_gun_pixel_mapper
      PORT MAP (
         gun_px_idx     => gun_px_idx,
         gun_x_center_q => gun_x_q,
         gun_color      => gun_color,
         gun_idx_x      => gun_x,
         gun_idx_y      => gun_y
      );

END struct;
