-- VHDL Entity alien_game_lib.c4_t1_gun_ctrl.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 12:25:34  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_gun_ctrl IS
   PORT( 
      btn_left  : IN     std_logic;
      btn_right : IN     std_logic;
      clk       : IN     std_logic;
      enable    : IN     std_logic;
      rst_n     : IN     std_logic;
      gun_x_q   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_gun_ctrl ;

--
-- VHDL Architecture alien_game_lib.c4_t1_gun_ctrl.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 13:24:10  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_gun_ctrl IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout         : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1        : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2        : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3        : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4        : std_logic_vector(7 DOWNTO 0);
   SIGNAL fout         : std_logic;
   SIGNAL fout1        : std_logic;
   SIGNAL sel2         : std_logic;
   SIGNAL x_next       : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_step_left  : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_step_right : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL gun_x_q_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'left_shifter' of 'fixshift'
   SIGNAL mw_left_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'right_shifter' of 'fixshift'
   SIGNAL mw_right_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   gun_x_q_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_0reg_cval <= "00000000";
         ELSIF (enable = '1') THEN
            mw_U_0reg_cval <= x_next;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'greater_than' of 'comp'
   greater_thancombo_proc : PROCESS (dout, dout1)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(dout) > unsigned(dout1)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS greater_thancombo_proc;

   -- ModuleWare code(v1.12) for instance 'less_than' of 'comp'
   less_thancombo_proc : PROCESS (dout2, dout3)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(dout2) < unsigned(dout3)) THEN
         temp_lout := '1';
      END IF;
   fout1 <= temp_lout;
   END PROCESS less_thancombo_proc;

   -- ModuleWare code(v1.12) for instance 'left_edge' of 'constval'
   dout3 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'right_edge' of 'constval'
   dout1 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'left_shifter' of 'fixshift'
   dout2 <= mw_left_shiftertemp_dout;
   left_shiftercombo_proc: PROCESS (x_step_right)
   BEGIN
      mw_left_shiftertemp_dout <= (OTHERS => '0');
      mw_left_shiftertemp_dout(7 DOWNTO 1) <= x_step_right(6 + 0 DOWNTO 0);
   END PROCESS left_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'right_shifter' of 'fixshift'
   dout <= mw_right_shiftertemp_dout;
   right_shiftercombo_proc: PROCESS (gun_x_q_internal)
   BEGIN
      mw_right_shiftertemp_dout <= (OTHERS => '0');
      mw_right_shiftertemp_dout(6 DOWNTO 0) <= gun_x_q_internal(7 + 0 DOWNTO 1 + 0);
   END PROCESS right_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(gun_x_q_internal, dout4, btn_right)
   BEGIN
      CASE btn_right IS
      WHEN '0' => x_step_right <= gun_x_q_internal;
      WHEN '1' => x_step_right <= dout4;
      WHEN OTHERS => x_step_right <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(dout, dout1, fout)
   BEGIN
      CASE fout IS
      WHEN '0' => dout4 <= dout;
      WHEN '1' => dout4 <= dout1;
      WHEN OTHERS => dout4 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(dout2, dout3, fout1)
   BEGIN
      CASE fout1 IS
      WHEN '0' => x_step_left <= dout2;
      WHEN '1' => x_step_left <= dout3;
      WHEN OTHERS => x_step_left <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   gun_x_q <= gun_x_q_internal;

END struct;
