-- VHDL Entity alien_game_lib.c4_t1_gun_pixel_mapper.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 16:26:55  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_gun_pixel_mapper IS
   PORT( 
      gun_px_idx     : IN     std_logic_vector (1 DOWNTO 0);
      gun_x_center_q : IN     std_logic_vector (7 DOWNTO 0);
      gun_color      : OUT    std_logic_vector (23 DOWNTO 0);
      gun_idx_x      : OUT    std_logic_vector (7 DOWNTO 0);
      gun_idx_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c4_t1_gun_pixel_mapper ;

--
-- VHDL Architecture alien_game_lib.c4_t1_gun_pixel_mapper.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 16:26:52  2.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_gun_pixel_mapper IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL gun_x_left  : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_x_right : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_y_base  : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_y_top   : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'fixshift'
   SIGNAL mw_U_0temp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'left_shifter' of 'fixshift'
   SIGNAL mw_left_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'right_shifter' of 'fixshift'
   SIGNAL mw_right_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'gun_color' of 'constval'
   gun_color <= "111111110000000000000000";

   -- ModuleWare code(v1.12) for instance 'gun_y_base' of 'constval'
   gun_y_base <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'fixshift'
   gun_y_top <= mw_U_0temp_dout;
   u_0combo_proc: PROCESS (gun_y_base)
   BEGIN
      mw_U_0temp_dout <= (OTHERS => '0');
      mw_U_0temp_dout(7 DOWNTO 1) <= gun_y_base(6 + 0 DOWNTO 0);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'left_shifter' of 'fixshift'
   gun_x_right <= mw_left_shiftertemp_dout;
   left_shiftercombo_proc: PROCESS (gun_x_center_q)
   BEGIN
      mw_left_shiftertemp_dout <= (OTHERS => '0');
      mw_left_shiftertemp_dout(7 DOWNTO 1) <= gun_x_center_q(6 + 0 DOWNTO 0);
   END PROCESS left_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'right_shifter' of 'fixshift'
   gun_x_left <= mw_right_shiftertemp_dout;
   right_shiftercombo_proc: PROCESS (gun_x_center_q)
   BEGIN
      mw_right_shiftertemp_dout <= (OTHERS => '0');
      mw_right_shiftertemp_dout(6 DOWNTO 0) <= gun_x_center_q(7 + 0 DOWNTO 1 + 0);
   END PROCESS right_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(gun_x_left, gun_x_right, gun_px_idx)
   BEGIN
      CASE gun_px_idx(1) IS
      WHEN '0' => gun_idx_x <= gun_x_left;
      WHEN '1' => gun_idx_x <= gun_x_right;
      WHEN OTHERS => gun_idx_x <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(gun_y_base, gun_y_top, gun_px_idx)
   BEGIN
      CASE gun_px_idx(0) IS
      WHEN '0' => gun_idx_y <= gun_y_base;
      WHEN '1' => gun_idx_y <= gun_y_top;
      WHEN OTHERS => gun_idx_y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
