-- VHDL Entity alien_game_lib.c5_b2_gamma_fsm.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 14:02:28 19.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_b2_gamma_fsm IS
   PORT( 
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      rx_rdy   : IN     std_logic;
      bit_out  : OUT    std_logic;
      lat      : OUT    std_logic;
      sb       : OUT    std_logic;
      transmit : OUT    std_logic
   );

-- Declarations

END c5_b2_gamma_fsm ;

--
-- VHDL Architecture alien_game_lib.c5_b2_gamma_fsm.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:32:32 20.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_b2_gamma_fsm IS

   -- Architecture Declarations
   SIGNAL bit_cnt : integer RANGE 143 DOWNTO 0;  
   SIGNAL gamma_shift : std_ulogic_vector(17 DOWNTO 0);  

   TYPE STATE_TYPE IS (
      RESET,
      WAIT_READY,
      SEND_BIT,
      LATCH,
      CHECK_DONE,
      DONE
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= RESET;
         -- Default Reset Values
         bit_cnt <= 0;
         gamma_shift <= "001110111111111011";
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;

         -- Combined Actions
         CASE current_state IS
            WHEN RESET => 
               bit_cnt <= 0;
               gamma_shift <= "111011111111001110";
            WHEN SEND_BIT => 
               gamma_shift <= gamma_shift(16 downto 0) & '0';
            WHEN CHECK_DONE => 
               if bit_cnt < 143 then
                    bit_cnt <= bit_cnt + 1;
               end if;
               
               if (bit_cnt mod 18 = 17) then
                   gamma_shift <= "001110111111111011";
               end if;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      bit_cnt,
      current_state,
      rst_n,
      rx_rdy
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN RESET => 
            IF (rst_n = '1') THEN 
               next_state <= WAIT_READY;
            ELSE
               next_state <= RESET;
            END IF;
         WHEN WAIT_READY => 
            IF (rx_rdy = '1') THEN 
               next_state <= SEND_BIT;
            ELSE
               next_state <= WAIT_READY;
            END IF;
         WHEN SEND_BIT => 
            IF (TRUE) THEN 
               next_state <= CHECK_DONE;
            ELSE
               next_state <= SEND_BIT;
            END IF;
         WHEN LATCH => 
            IF (TRUE) THEN 
               next_state <= DONE;
            ELSE
               next_state <= LATCH;
            END IF;
         WHEN CHECK_DONE => 
            IF (bit_cnt = 143) THEN 
               next_state <= LATCH;
            ELSIF (bit_cnt < 143) THEN 
               next_state <= WAIT_READY;
            ELSE
               next_state <= CHECK_DONE;
            END IF;
         WHEN DONE => 
            IF (rst_n = '0') THEN 
               next_state <= RESET;
            ELSE
               next_state <= DONE;
            END IF;
         WHEN OTHERS =>
            next_state <= RESET;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state,
      gamma_shift
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      bit_out <= '0';
      lat <= '0';
      sb <= '1';
      transmit <= '0';
      -- Global Actions
      transmit <= '0' ;
      sb <= '0' ;
      lat <= '0' ;
      bit_out <= gamma_shift(17);

      -- Combined Actions
      CASE current_state IS
         WHEN WAIT_READY => 
            bit_out <= gamma_shift(17);
         WHEN SEND_BIT => 
            transmit <= '1' ;
         WHEN LATCH => 
            lat <= '1' ;
         WHEN DONE => 
            sb <= '1' ;
            lat <= '0' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
