-- VHDL Entity alien_game_lib.c5_b1_Serial_Data_Transmit.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 12:58:00 18.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_b1_Serial_Data_Transmit IS
   PORT( 
      bit_in   : IN     std_logic;
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      transmit : IN     std_logic;
      ready    : OUT    std_logic;
      s_clk    : OUT    std_logic;
      s_sda    : OUT    std_logic
   );

-- Declarations

END c5_b1_Serial_Data_Transmit ;

--
-- VHDL Architecture alien_game_lib.c5_b1_Serial_Data_Transmit.fsm
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:56:11 18.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_b1_Serial_Data_Transmit IS

   TYPE STATE_TYPE IS (
      WAIT_READY,
      DO_WRITE
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL ready_cld : std_logic ;
   SIGNAL s_clk_int : std_logic ;
   SIGNAL s_sda_int : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= WAIT_READY;
         -- Default Reset Values
         ready_cld <= '1';
         s_clk <= '0';
         s_sda <= '0';
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         -- Registered output assignments
         s_clk <= s_clk_int;
         s_sda <= s_sda_int;
         -- Default Assignment To Internals
         ready_cld <= '0';

         -- Combined Actions
         CASE current_state IS
            WHEN WAIT_READY => 
               IF (transmit = '1') THEN 
                  ready_cld <= '0';
               END IF;
            WHEN DO_WRITE => 
               IF (transmit = '0') THEN 
                  ready_cld <= '1';
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN WAIT_READY => 
            IF (transmit = '1') THEN 
               next_state <= DO_WRITE;
            ELSIF (transmit = '0') THEN 
               next_state <= WAIT_READY;
            ELSE
               next_state <= WAIT_READY;
            END IF;
         WHEN DO_WRITE => 
            IF (transmit = '0') THEN 
               next_state <= WAIT_READY;
            ELSE
               next_state <= DO_WRITE;
            END IF;
         WHEN OTHERS =>
            next_state <= WAIT_READY;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      bit_in,
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      s_clk_int <= '0';
      s_sda_int <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN WAIT_READY => 
            IF (transmit = '1') THEN 
               s_clk_int <= '1';
               s_sda_int <= bit_in;
            ELSIF (transmit = '0') THEN 
               s_clk_int <= '0';
            END IF;
         WHEN DO_WRITE => 
            IF (transmit = '0') THEN 
               s_clk_int <= '0';
            END IF;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   ready <= ready_cld;
END fsm;
