-- VHDL Entity alien_game_lib.c5_b1_serial_tx_fsm.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:21:29 19.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_b1_serial_tx_fsm IS
   PORT( 
      bit_in   : IN     std_logic;
      clk      : IN     std_logic;
      rst_n    : IN     std_logic;
      transmit : IN     std_logic;
      ready    : OUT    std_logic;
      s_clk    : OUT    std_logic;
      s_sda    : OUT    std_logic
   );

-- Declarations

END c5_b1_serial_tx_fsm ;

--
-- VHDL Architecture alien_game_lib.c5_b1_serial_tx_fsm.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-309-SPC)
--          at - 11:21:29 19.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_b1_serial_tx_fsm IS

   -- Architecture Declarations
   SIGNAL bit_lat : std_logic;  
   SIGNAL cnt : integer RANGE 2 DOWNTO 0;  

   TYPE STATE_TYPE IS (
      IDLE,
      SET_DATA,
      CLK_LOW,
      CLK_HIGH
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= IDLE;
         -- Default Reset Values
         cnt <= 0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;

         -- Combined Actions
         CASE current_state IS
            WHEN SET_DATA => 
               bit_lat <= bit_in ;
               IF (TRUE) THEN 
                  cnt <= 0 ;
               END IF;
            WHEN CLK_LOW => 
               cnt <= cnt  + 1;
               IF (cnt = 1) THEN 
                  cnt <= 0 ;
               END IF;
            WHEN CLK_HIGH => 
               cnt <= cnt  + 1;
               IF (cnt = 1) THEN 
                  cnt <= 0;
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      cnt,
      current_state,
      transmit
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN IDLE => 
            IF (transmit = '1') THEN 
               next_state <= SET_DATA;
            ELSE
               next_state <= IDLE;
            END IF;
         WHEN SET_DATA => 
            IF (TRUE) THEN 
               next_state <= CLK_LOW;
            ELSE
               next_state <= SET_DATA;
            END IF;
         WHEN CLK_LOW => 
            IF (cnt = 1) THEN 
               next_state <= CLK_HIGH;
            ELSIF (cnt < 1) THEN 
               next_state <= CLK_LOW;
            ELSE
               next_state <= CLK_LOW;
            END IF;
         WHEN CLK_HIGH => 
            IF (cnt = 1) THEN 
               next_state <= IDLE;
            ELSIF (cnt < 1) THEN 
               next_state <= CLK_HIGH;
            ELSE
               next_state <= CLK_HIGH;
            END IF;
         WHEN OTHERS =>
            next_state <= IDLE;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      bit_lat,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Global Actions
      s_clk <= '0';
      ready <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN IDLE => 
            ready <= '1' ;
            s_clk <= '0' ;
         WHEN SET_DATA => 
            ready <= '0' ;
         WHEN CLK_LOW => 
            s_clk <= '0' ;
            s_sda <= bit_lat ;
         WHEN CLK_HIGH => 
            s_clk <= '1' ;
            s_sda <= bit_lat ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
