-- VHDL Entity alien_game_lib.c5_t2_game_logic_static.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:26:58  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t2_game_logic_static IS
   PORT( 
      frame_done : OUT    std_logic;
      write      : OUT    std_logic
   );

-- Declarations

END c5_t2_game_logic_static ;

--
-- VHDL Architecture alien_game_lib.c5_t2_game_logic_static.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:26:58  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t2_game_logic_static IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_color    : std_logic_vector(23 DOWNTO 0);
   SIGNAL alien_defeated : std_logic;
   SIGNAL alien_x        : std_logic_vector(7 DOWNTO 0);
   SIGNAL alien_y        : std_logic_vector(7 DOWNTO 0);
   SIGNAL btn            : std_logic_vector(3 DOWNTO 0);
   SIGNAL bullet_color   : std_logic_vector(23 DOWNTO 0);
   SIGNAL bullet_x       : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_y       : std_logic_vector(7 DOWNTO 0);
   SIGNAL clk            : std_logic;
   SIGNAL color_BGR      : std_logic_vector(23 DOWNTO 0);
   SIGNAL enable         : std_logic;
   SIGNAL gun_color      : std_logic_vector(23 DOWNTO 0);
   SIGNAL gun_px_idx     : std_logic_vector(1 DOWNTO 0);
   SIGNAL gun_x          : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_y          : std_logic_vector(7 DOWNTO 0);
   SIGNAL hit            : std_logic;
   SIGNAL module_select  : std_logic_vector(1 DOWNTO 0);
   SIGNAL rst_n          : std_logic;
   SIGNAL victory_color  : std_logic_vector(23 DOWNTO 0);
   SIGNAL victory_x      : std_logic_vector(7 DOWNTO 0);
   SIGNAL victory_y      : std_logic_vector(7 DOWNTO 0);
   SIGNAL write_ready    : std_logic;
   SIGNAL x_coord        : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord        : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c4_b1_bullet_fsm
   PORT (
      btn_0        : IN     std_logic ;
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      gun_x        : IN     std_logic_vector (7 DOWNTO 0);
      rst_n        : IN     std_logic ;
      bullet_color : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x     : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_top_gun
   PORT (
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic ;
      enable     : IN     std_logic ;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic ;
      gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      gun_x      : OUT    std_logic_vector (7 DOWNTO 0);
      gun_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c5_t1_write_sequencer_fsm2
   PORT (
      alien_defeated : IN     std_logic ;
      clk            : IN     std_logic ;
      rst            : IN     std_logic ;
      write_ready    : IN     std_logic ;
      enable         : OUT    std_logic ;
      frame_done     : OUT    std_logic ;
      gun_px_idx     : OUT    std_logic_vector (1 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c6_b1_victory_top
   PORT (
      clk           : IN     std_logic ;
      rst_n         : IN     std_logic ;
      victory_color : OUT    std_logic_vector (23 DOWNTO 0);
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0);
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c6_t1_hit_detect
   PORT (
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      hit            : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c7_t1_v0_alien
   PORT (
      clk            : IN     std_logic ;
      enable         : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      alien_defeated : OUT    std_logic ;
      alien_x        : OUT    std_logic_vector (7 DOWNTO 0);
      alien_y        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_b1_bullet_fsm USE ENTITY alien_game_lib.c4_b1_bullet_fsm;
   FOR ALL : c4_t1_top_gun USE ENTITY alien_game_lib.c4_t1_top_gun;
   FOR ALL : c5_t1_write_sequencer_fsm2 USE ENTITY alien_game_lib.c5_t1_write_sequencer_fsm2;
   FOR ALL : c6_b1_victory_top USE ENTITY alien_game_lib.c6_b1_victory_top;
   FOR ALL : c6_t1_hit_detect USE ENTITY alien_game_lib.c6_t1_hit_detect;
   FOR ALL : c7_t1_v0_alien USE ENTITY alien_game_lib.c7_t1_v0_alien;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'pixel_color' of 'mux'
   pixel_colorcombo_proc: PROCESS(alien_color, gun_color, bullet_color, 
                                  victory_color, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => color_BGR <= alien_color;
      WHEN "01" => color_BGR <= gun_color;
      WHEN "10" => color_BGR <= bullet_color;
      WHEN "11" => color_BGR <= victory_color;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_colorcombo_proc;

   -- ModuleWare code(v1.12) for instance 'pixel_x' of 'mux'
   pixel_xcombo_proc: PROCESS(alien_x, gun_x, bullet_x, victory_x, 
                              module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => x_coord <= alien_x;
      WHEN "01" => x_coord <= gun_x;
      WHEN "10" => x_coord <= bullet_x;
      WHEN "11" => x_coord <= victory_x;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_xcombo_proc;

   -- ModuleWare code(v1.12) for instance 'pixel_y' of 'mux'
   pixel_ycombo_proc: PROCESS(alien_y, gun_y, bullet_y, victory_y, 
                              module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => y_coord <= alien_y;
      WHEN "01" => y_coord <= gun_y;
      WHEN "10" => y_coord <= bullet_y;
      WHEN "11" => y_coord <= victory_y;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_ycombo_proc;

   -- Instance port mappings.
   U_3 : c4_b1_bullet_fsm
      PORT MAP (
         btn_0        => btn(0),
         clk          => clk,
         enable       => enable,
         gun_x        => gun_x,
         rst_n        => rst_n,
         bullet_color => bullet_color,
         bullet_x     => bullet_x,
         bullet_y     => bullet_y
      );
   U_1 : c4_t1_top_gun
      PORT MAP (
         btn        => btn,
         clk        => clk,
         enable     => enable,
         gun_px_idx => gun_px_idx,
         rst_n      => rst_n,
         gun_color  => gun_color,
         gun_x      => gun_x,
         gun_y      => gun_y
      );
   U_0 : c5_t1_write_sequencer_fsm2
      PORT MAP (
         alien_defeated => alien_defeated,
         clk            => clk,
         rst            => rst_n,
         write_ready    => write_ready,
         enable         => enable,
         frame_done     => frame_done,
         gun_px_idx     => gun_px_idx,
         module_select  => module_select,
         write          => write
      );
   U_4 : c6_b1_victory_top
      PORT MAP (
         clk           => clk,
         rst_n         => rst_n,
         victory_color => victory_color,
         victory_x     => victory_x,
         victory_y     => victory_y
      );
   U_6 : c6_t1_hit_detect
      PORT MAP (
         alien_x_coord  => alien_x,
         alien_y_coord  => alien_y,
         bullet_x_coord => bullet_x,
         bullet_y_coord => bullet_y,
         clk            => clk,
         rst_n          => rst_n,
         hit            => hit
      );
   U_2 : c7_t1_v0_alien
      PORT MAP (
         clk            => clk,
         enable         => enable,
         hit            => hit,
         rst_n          => rst_n,
         alien_color    => alien_color,
         alien_defeated => alien_defeated,
         alien_x        => alien_x,
         alien_y        => alien_y
      );

END struct;
