-- VHDL Entity alien_game_lib.c5_t1_write_sequencer_fsm.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-308-SPC)
--          at - 13:29:06 11.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_write_sequencer_fsm IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      write_ready    : IN     std_logic;
      enable         : OUT    std_logic;
      frame_done     : OUT    std_logic;
      gun_px_idx     : OUT    std_logic_vector (1 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic
   );

-- Declarations

END c5_t1_write_sequencer_fsm ;

--
-- VHDL Architecture alien_game_lib.c5_t1_write_sequencer_fsm.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-317-SPC)
--          at - 15:38:55 13.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_t1_write_sequencer_fsm IS

   -- Architecture Declarations
   SIGNAL fast_sim : std_logic;  
   SIGNAL step_q : std_logic_vector(2 DOWNTO 0);  
   SIGNAL write_pulse : std_logic;  

   TYPE STATE_TYPE IS (
      WAIT_READY,
      DO_WRITE,
      DO_FRAME_DONE,
      DO_ENABLE
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL write_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= WAIT_READY;
      ELSIF (clk'EVENT AND clk = '1') THEN
         write_cld <= write_pulse;
         -- Default Assignment To Internals
         fast_sim <= '1';
         -- Global Internal Actions
         write_cld <= '0' ;

         -- Combined Actions
         CASE current_state IS
            WHEN DO_WRITE => 
               
               case step_q is
                 when "000" => step_q <= "001";
                 when "001" => step_q <= "010";
                 when "010" => step_q <= "011";
                 when "011" => step_q <= "100";
                 when "100" => step_q <= "101";  
                 when "101" => step_q <= "000";  
                 when others => step_q <= "000";
               end case;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      step_q,
      write_ready
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN WAIT_READY => 
            IF (write_ready = '1') THEN 
               next_state <= DO_WRITE;
            ELSE
               next_state <= WAIT_READY;
            END IF;
         WHEN DO_WRITE => 
            IF (step_q <= "000") THEN 
               next_state <= DO_FRAME_DONE;
            ELSE
               next_state <= DO_WRITE;
            END IF;
         WHEN DO_FRAME_DONE => 
            IF (TRUE) THEN 
               next_state <= DO_ENABLE;
            ELSE
               next_state <= DO_FRAME_DONE;
            END IF;
         WHEN DO_ENABLE => 
            IF (TRUE) THEN 
               next_state <= WAIT_READY;
            ELSE
               next_state <= DO_ENABLE;
            END IF;
         WHEN OTHERS =>
            next_state <= WAIT_READY;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state,
      step_q
   )
   -----------------------------------------------------------------
   BEGIN
      -- Global Actions
      frame_done <= '0' ;
      enable <= '0' ;
      module_select <= "00" ;
      gun_px_idx <= "00" ;
      write_pulse <= '0' ;

      -- Combined Actions
      CASE current_state IS
         WHEN DO_WRITE => 
            write_pulse <= '1' ;
            if step_q = "000" then
                module_select <= "00";
            
            elsif step_q = "001" then
                module_select <= "01";
                gun_px_idx <= "00";
            
            elsif step_q = "010" then
                module_select <= "01";
                gun_px_idx <= "01";
            
            elsif step_q = "011" then
                module_select <= "01";
                gun_px_idx <= "10";
            
            elsif step_q = "100" then
                module_select <= "01";
                gun_px_idx <= "11";
            
            elsif step_q = "101" then
                module_select <= "10";
            
            end if;
         WHEN DO_FRAME_DONE => 
            frame_done <= '1';
         WHEN DO_ENABLE => 
            enable <= '1' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   write <= write_cld;
END fsm;
