-- VHDL Entity alien_game_lib.c5_t2_game_logic.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-317-SPC)
--          at - 15:02:37 13.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t2_game_logic IS
   PORT( 
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic;
      rst_n       : IN     std_logic;
      write_ready : IN     std_logic;
      color_BGR   : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done  : OUT    std_logic;
      write       : OUT    std_logic;
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c5_t2_game_logic ;

--
-- VHDL Architecture alien_game_lib.c5_t2_game_logic.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-317-SPC)
--          at - 15:02:37 13.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t2_game_logic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_color   : std_logic_vector(23 DOWNTO 0);
   SIGNAL alien_x       : std_logic_vector(7 DOWNTO 0);
   SIGNAL alien_y       : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_color  : std_logic_vector(23 DOWNTO 0);
   SIGNAL bullet_x      : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_y      : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout          : std_logic;
   SIGNAL enable        : std_logic;
   SIGNAL gun_color     : std_logic_vector(23 DOWNTO 0);
   SIGNAL gun_px_idx    : std_logic_vector(1 DOWNTO 0);
   SIGNAL gun_x         : std_logic_vector(7 DOWNTO 0);
   SIGNAL gun_y         : std_logic_vector(7 DOWNTO 0);
   SIGNAL module_select : std_logic_vector(1 DOWNTO 0);


   -- Component Declarations
   COMPONENT c3_t1_basic_alien
   PORT (
      clk         : IN     std_logic ;
      enable      : IN     std_logic ;
      hit         : IN     std_logic ;
      rst_n       : IN     std_logic ;
      alien_color : OUT    std_logic_vector (23 DOWNTO 0);
      alien_x     : OUT    std_logic_vector (7 DOWNTO 0);
      alien_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_b1_bullet_fsm
   PORT (
      btn_0        : IN     std_logic ;
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      gun_x        : IN     std_logic_vector (7 DOWNTO 0);
      rst_n        : IN     std_logic ;
      bullet_color : OUT    std_logic_vector (23 DOWNTO 0);
      bullet_x     : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c4_t1_top_gun
   PORT (
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic ;
      enable     : IN     std_logic ;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic ;
      gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      gun_x      : OUT    std_logic_vector (7 DOWNTO 0);
      gun_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c5_t1_write_sequencer_fsm
   PORT (
      alien_defeated : IN     std_logic ;
      clk            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      write_ready    : IN     std_logic ;
      enable         : OUT    std_logic ;
      frame_done     : OUT    std_logic ;
      gun_px_idx     : OUT    std_logic_vector (1 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_basic_alien USE ENTITY alien_game_lib.c3_t1_basic_alien;
   FOR ALL : c4_b1_bullet_fsm USE ENTITY alien_game_lib.c4_b1_bullet_fsm;
   FOR ALL : c4_t1_top_gun USE ENTITY alien_game_lib.c4_t1_top_gun;
   FOR ALL : c5_t1_write_sequencer_fsm USE ENTITY alien_game_lib.c5_t1_write_sequencer_fsm;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'pixel_color' of 'mux'
   pixel_colorcombo_proc: PROCESS(alien_color, gun_color, bullet_color, 
                                  module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => color_BGR <= alien_color;
      WHEN "01" => color_BGR <= gun_color;
      WHEN "10" => color_BGR <= bullet_color;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_colorcombo_proc;

   -- ModuleWare code(v1.12) for instance 'pixel_x' of 'mux'
   pixel_xcombo_proc: PROCESS(alien_x, gun_x, bullet_x, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => x_coord <= alien_x;
      WHEN "01" => x_coord <= gun_x;
      WHEN "10" => x_coord <= bullet_x;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_xcombo_proc;

   -- ModuleWare code(v1.12) for instance 'pixel_y' of 'mux'
   pixel_ycombo_proc: PROCESS(alien_y, gun_y, bullet_y, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => y_coord <= alien_y;
      WHEN "01" => y_coord <= gun_y;
      WHEN "10" => y_coord <= bullet_y;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS pixel_ycombo_proc;

   -- Instance port mappings.
   U_2 : c3_t1_basic_alien
      PORT MAP (
         clk         => clk,
         enable      => enable,
         hit         => btn(0),
         rst_n       => rst_n,
         alien_color => alien_color,
         alien_x     => alien_x,
         alien_y     => alien_y
      );
   U_3 : c4_b1_bullet_fsm
      PORT MAP (
         btn_0        => btn(0),
         clk          => clk,
         enable       => enable,
         gun_x        => gun_x,
         rst_n        => rst_n,
         bullet_color => bullet_color,
         bullet_x     => bullet_x,
         bullet_y     => bullet_y
      );
   U_1 : c4_t1_top_gun
      PORT MAP (
         btn        => btn,
         clk        => clk,
         enable     => enable,
         gun_px_idx => gun_px_idx,
         rst_n      => rst_n,
         gun_color  => gun_color,
         gun_x      => gun_x,
         gun_y      => gun_y
      );
   U_0 : c5_t1_write_sequencer_fsm
      PORT MAP (
         alien_defeated => dout,
         clk            => clk,
         rst_n          => rst_n,
         write_ready    => write_ready,
         enable         => enable,
         frame_done     => frame_done,
         gun_px_idx     => gun_px_idx,
         module_select  => module_select,
         write          => write
      );

END struct;
