-- VHDL Entity alien_game_lib.c5_t1_write_sequencer_fsm2.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:12:22  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_write_sequencer_fsm2 IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      rst            : IN     std_logic;
      write_ready    : IN     std_logic;
      enable         : OUT    std_logic;
      frame_done     : OUT    std_logic;
      gun_px_idx     : OUT    std_logic_vector (1 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic
   );

-- Declarations

END c5_t1_write_sequencer_fsm2 ;

--
-- VHDL Architecture alien_game_lib.c5_t1_write_sequencer_fsm2.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:14:25  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c5_t1_write_sequencer_fsm2 IS

   -- Architecture Declarations
   SIGNAL step_q : integer RANGE 5 DOWNTO 0;  
   SIGNAL tick_cnt : integer RANGE 20_000_000 DOWNTO 0;  

   TYPE STATE_TYPE IS (
      WAIT_READY,
      DO_WRITE,
      WAIT_TICK,
      DO_FRAME_DONE,
      DO_ENABLE
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= WAIT_READY;
         -- Default Reset Values
         step_q <= 0;
         tick_cnt <= 0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;

         -- Combined Actions
         CASE current_state IS
            WHEN WAIT_TICK => 
               tick_cnt <= tick_cnt +1;
            WHEN DO_ENABLE => 
               IF (TRUE) THEN 
                  tick_cnt <= 0;
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      alien_defeated,
      current_state,
      step_q,
      tick_cnt,
      write_ready
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN WAIT_READY => 
            IF (write_ready = '1') THEN 
               next_state <= DO_WRITE;
            ELSE
               next_state <= WAIT_READY;
            END IF;
         WHEN DO_WRITE => 
            IF ((alien_defeated = '0' AND step_q = 5) 
                OR (alien_defeated = '1' AND step_q = 5)) THEN 
               next_state <= DO_FRAME_DONE;
            ELSE
               next_state <= DO_WRITE;
            END IF;
         WHEN WAIT_TICK => 
            IF (tick_cnt = 20_000_000) THEN 
               next_state <= WAIT_READY;
            ELSIF (tick_cnt < 20_000_000) THEN 
               next_state <= WAIT_TICK;
            ELSE
               next_state <= WAIT_TICK;
            END IF;
         WHEN DO_FRAME_DONE => 
            IF (TRUE) THEN 
               next_state <= DO_ENABLE;
            ELSIF ((alien_defeated = '0' AND step_q < 5) 
                   OR (alien_defeated = '1' AND step_q < 5)) THEN 
               next_state <= DO_WRITE;
            ELSE
               next_state <= DO_FRAME_DONE;
            END IF;
         WHEN DO_ENABLE => 
            IF (TRUE) THEN 
               next_state <= WAIT_TICK;
            ELSE
               next_state <= DO_ENABLE;
            END IF;
         WHEN OTHERS =>
            next_state <= WAIT_READY;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      alien_defeated,
      current_state,
      step_q
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN DO_WRITE => 
            write <= '1';
            
            if alien_defeated = '1' then
                module_select <= "11";          -- victory
            else
                if    step_q = 0 then
                 module_select <= "00"; -- alien
            
                elsif step_q = 1 then
                   module_select <= "01"; gun_px_idx <= "00";
            
                elsif step_q = 2 then
                   module_select <= "01"; gun_px_idx <= "01";
            
                elsif step_q = 3 then
                  module_select <= "01"; gun_px_idx <= "10";
            
                elsif step_q = 4 then
                   module_select <= "01"; gun_px_idx <= "11";
            
                elsif step_q = 5 then
                   module_select <= "10"; -- bullet
            
                end if;
            end if;
         WHEN DO_FRAME_DONE => 
            frame_done <= '1';
         WHEN DO_ENABLE => 
            enable <= '1' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
