-- VHDL Entity alien_game_lib.c6_b2_register_bank.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:30:22  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b2_register_bank IS
   PORT( 
      clk        : IN     std_logic;
      frame_done : IN     std_logic;
      pixd_in    : IN     std_logic_vector (23 DOWNTO 0);
      rst        : IN     std_logic;
      write      : IN     std_logic;
      xr         : IN     std_logic_vector (7 DOWNTO 0);
      xw         : IN     std_logic_vector (7 DOWNTO 0);
      yr         : IN     std_logic_vector (7 DOWNTO 0);
      yw         : IN     std_logic_vector (7 DOWNTO 0);
      pixd_out   : OUT    std_logic_vector (23 DOWNTO 0);
      w_rdy      : OUT    std_logic
   );

-- Declarations

END c6_b2_register_bank ;

--
-- VHDL Architecture alien_game_lib.c6_b2_register_bank.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 13:00:48  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_b2_register_bank IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clear_mem0  : std_logic;
   SIGNAL clear_mem1  : std_logic;
   SIGNAL dout        : std_logic;
   SIGNAL dout1       : std_logic;
   SIGNAL dout2       : std_logic;
   SIGNAL pixel_in    : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out   : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out1  : std_logic_vector(23 DOWNTO 0);
   SIGNAL rst_n       : std_logic;
   SIGNAL wr_sel      : std_logic;
   SIGNAL write_ready : std_logic;
   SIGNAL x_read      : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_write     : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_read      : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_write     : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL w_rdy_internal : std_logic;


   -- Component Declarations
   COMPONENT c6_b2_register_matrix
   PORT (
      clear     : IN     std_logic ;
      clk       : IN     std_logic ;
      pixel_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic ;
      we        : IN     std_logic ;
      x_read    : IN     std_logic_vector (7 DOWNTO 0);
      x_write   : IN     std_logic_vector (7 DOWNTO 0);
      y_read    : IN     std_logic_vector (7 DOWNTO 0);
      y_write   : IN     std_logic_vector (7 DOWNTO 0);
      pixel_out : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c6_t1_register_controller
   PORT (
      clk        : IN     std_logic ;
      frame_done : IN     std_logic ;
      rst        : IN     std_logic ;
      clear_mem0 : OUT    std_logic ;
      clear_mem1 : OUT    std_logic ;
      w_rdy      : OUT    std_logic ;
      wr_sel     : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b2_register_matrix USE ENTITY alien_game_lib.c6_b2_register_matrix;
   FOR ALL : c6_t1_register_controller USE ENTITY alien_game_lib.c6_t1_register_controller;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   write_ready <= write AND w_rdy_internal;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout1 <= wr_sel AND write_ready;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout2 <= dout AND write_ready;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'inv'
   dout <= NOT(wr_sel);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(pixel_out, pixel_out1, wr_sel)
   BEGIN
      CASE wr_sel IS
      WHEN '0' => pixd_out <= pixel_out;
      WHEN '1' => pixd_out <= pixel_out1;
      WHEN OTHERS => pixd_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_0 : c6_b2_register_matrix
      PORT MAP (
         clear     => clear_mem0,
         clk       => clk,
         pixel_in  => pixel_in,
         rst_n     => rst_n,
         we        => dout1,
         x_read    => x_read,
         x_write   => x_write,
         y_read    => y_read,
         y_write   => y_write,
         pixel_out => pixel_out
      );
   U_1 : c6_b2_register_matrix
      PORT MAP (
         clear     => clear_mem1,
         clk       => clk,
         pixel_in  => pixel_in,
         rst_n     => rst_n,
         we        => dout2,
         x_read    => x_read,
         x_write   => x_write,
         y_read    => y_read,
         y_write   => y_write,
         pixel_out => pixel_out1
      );
   U_2 : c6_t1_register_controller
      PORT MAP (
         clk        => clk,
         frame_done => frame_done,
         rst        => rst,
         clear_mem0 => clear_mem0,
         clear_mem1 => clear_mem1,
         w_rdy      => w_rdy_internal,
         wr_sel     => wr_sel
      );

   -- Implicit buffered output assignments
   w_rdy <= w_rdy_internal;

END struct;
