-- VHDL Entity alien_game_lib.c6_b1_victory_symbol_for_test.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:11:55 24.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b1_victory_symbol_for_test IS
   PORT( 
      idx           : IN     std_logic_vector (1 DOWNTO 0)  := "00";
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"00FFFF";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00"
   );

-- Declarations

END c6_b1_victory_symbol_for_test ;

--
-- VHDL Architecture alien_game_lib.c6_b1_victory_symbol_for_test.tbl
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:20:49  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c6_b1_victory_symbol_for_test IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = "00") THEN
         victory_x <= X"02";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      ELSIF (idx = "01") THEN
         victory_x <= X"04";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      ELSIF (idx = "10") THEN
         victory_x <= X"08";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      ELSIF (idx = "11") THEN
         victory_x <= X"10";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
