-- VHDL Entity alien_game_lib.c6_b2_register_matrix.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:04:19  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b2_register_matrix IS
   PORT( 
      clear     : IN     std_logic;
      clk       : IN     std_logic;
      pixel_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic;
      we        : IN     std_logic;
      x_read    : IN     std_logic_vector (7 DOWNTO 0);
      x_write   : IN     std_logic_vector (7 DOWNTO 0);
      y_read    : IN     std_logic_vector (7 DOWNTO 0);
      y_write   : IN     std_logic_vector (7 DOWNTO 0);
      pixel_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c6_b2_register_matrix ;

--
-- VHDL Architecture alien_game_lib.c6_b2_register_matrix.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:07:24  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_b2_register_matrix IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout        : std_logic;
   SIGNAL dout1       : std_logic;
   SIGNAL dout2       : std_logic;
   SIGNAL dout3       : std_logic;
   SIGNAL dout4       : std_logic;
   SIGNAL dout5       : std_logic;
   SIGNAL dout6       : std_logic;
   SIGNAL dout7       : std_logic;
   SIGNAL pixel_out_0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_3 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_4 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_5 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_6 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_7 : std_logic_vector(23 DOWNTO 0);


   -- Component Declarations
   COMPONENT c6_b2_register_row
   PORT (
      clear    : IN     std_logic ;
      clk      : IN     std_logic ;
      pixel_in : IN     std_logic_vector (23 DOWNTO 0);
      rst_n    : IN     std_logic ;
      we       : IN     std_logic ;
      x_read   : IN     std_logic_vector (7 DOWNTO 0);
      x_write  : IN     std_logic_vector (7 DOWNTO 0);
      row_out  : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b2_register_row USE ENTITY alien_game_lib.c6_b2_register_row;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   dout <= we AND y_write(0);

   -- ModuleWare code(v1.12) for instance 'U_11' of 'and'
   dout1 <= we AND y_write(1);

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   dout2 <= we AND y_write(2);

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout3 <= we AND y_write(3);

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout4 <= we AND y_write(4);

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout5 <= we AND y_write(5);

   -- ModuleWare code(v1.12) for instance 'U_16' of 'and'
   dout6 <= we AND y_write(6);

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   dout7 <= we AND y_write(7);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'omux'
   u_8combo_proc: PROCESS(pixel_out_0, pixel_out_1, pixel_out_2, 
                          pixel_out_3, pixel_out_4, pixel_out_5, 
                          pixel_out_6, pixel_out_7, y_read)
   BEGIN
      pixel_out <= (OTHERS => 'X');
      CASE y_read IS
      WHEN "00000001" => pixel_out <= pixel_out_0;
      WHEN "00000010" => pixel_out <= pixel_out_1;
      WHEN "00000100" => pixel_out <= pixel_out_2;
      WHEN "00001000" => pixel_out <= pixel_out_3;
      WHEN "00010000" => pixel_out <= pixel_out_4;
      WHEN "00100000" => pixel_out <= pixel_out_5;
      WHEN "01000000" => pixel_out <= pixel_out_6;
      WHEN "10000000" => pixel_out <= pixel_out_7;
      WHEN OTHERS => pixel_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- Instance port mappings.
   U_0 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_0
      );
   U_1 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout1,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_1
      );
   U_2 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout2,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_2
      );
   U_3 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout3,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_3
      );
   U_4 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout4,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_4
      );
   U_5 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout5,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_5
      );
   U_6 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout6,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_6
      );
   U_7 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we       => dout7,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_7
      );

END struct;
