-- VHDL Entity alien_game_lib.c6_b2_register_bank.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:29:55  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b2_register_bank IS
   PORT( 
      clk        : IN     std_logic;
      frame_done : IN     std_logic;
      pixel_in   : IN     std_logic_vector (23 DOWNTO 0);
      rst_n      : IN     std_logic;
      write      : IN     std_logic;
      x_read     : IN     std_logic_vector (7 DOWNTO 0);
      x_write    : IN     std_logic_vector (7 DOWNTO 0);
      y_read     : IN     std_logic_vector (7 DOWNTO 0);
      y_write    : IN     std_logic_vector (7 DOWNTO 0);
      pixel_out  : OUT    std_logic_vector (23 DOWNTO 0);
      w_rdy      : OUT    std_logic
   );

-- Declarations

END c6_b2_register_bank ;

--
-- VHDL Architecture alien_game_lib.c6_b2_register_bank.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:42:24  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_b2_register_bank IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clear_mem0        : std_logic;
   SIGNAL clear_mem1        : std_logic;
   SIGNAL dout              : std_logic;
   SIGNAL dout1             : std_logic;
   SIGNAL dout2             : std_logic;
   SIGNAL dout3             : std_logic;
   SIGNAL pixel_out_matrix0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_matrix1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL wr_sel            : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL w_rdy_internal : std_logic;


   -- Component Declarations
   COMPONENT c6_b2_register_controller
   PORT (
      clk        : IN     std_logic ;
      frame_done : IN     std_logic ;
      rst        : IN     std_logic ;
      clear_mem0 : OUT    std_logic ;
      clear_mem1 : OUT    std_logic ;
      w_rdy      : OUT    std_logic ;
      wr_sel     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT c6_b2_register_matrix
   PORT (
      clear     : IN     std_logic ;
      clk       : IN     std_logic ;
      pixel_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic ;
      we        : IN     std_logic ;
      x_read    : IN     std_logic_vector (7 DOWNTO 0);
      x_write   : IN     std_logic_vector (7 DOWNTO 0);
      y_read    : IN     std_logic_vector (7 DOWNTO 0);
      y_write   : IN     std_logic_vector (7 DOWNTO 0);
      pixel_out : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b2_register_controller USE ENTITY alien_game_lib.c6_b2_register_controller;
   FOR ALL : c6_b2_register_matrix USE ENTITY alien_game_lib.c6_b2_register_matrix;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout <= write AND w_rdy_internal;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout2 <= dout3 AND wr_sel;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout1 <= dout AND wr_sel;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'inv'
   dout3 <= NOT(dout);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(pixel_out_matrix1, pixel_out_matrix0, wr_sel)
   BEGIN
      CASE wr_sel IS
      WHEN '0' => pixel_out <= pixel_out_matrix1;
      WHEN '1' => pixel_out <= pixel_out_matrix0;
      WHEN OTHERS => pixel_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_2 : c6_b2_register_controller
      PORT MAP (
         clk        => clk,
         frame_done => frame_done,
         rst        => rst_n,
         clear_mem0 => clear_mem0,
         clear_mem1 => clear_mem1,
         w_rdy      => w_rdy_internal,
         wr_sel     => wr_sel
      );
   U_0 : c6_b2_register_matrix
      PORT MAP (
         clear     => clear_mem0,
         clk       => clk,
         pixel_in  => pixel_in,
         rst_n     => rst_n,
         we        => dout2,
         x_read    => x_read,
         x_write   => x_write,
         y_read    => y_read,
         y_write   => y_write,
         pixel_out => pixel_out_matrix0
      );
   U_1 : c6_b2_register_matrix
      PORT MAP (
         clear     => clear_mem1,
         clk       => clk,
         pixel_in  => pixel_in,
         rst_n     => rst_n,
         we        => dout1,
         x_read    => x_read,
         x_write   => x_write,
         y_read    => y_read,
         y_write   => y_write,
         pixel_out => pixel_out_matrix1
      );

   -- Implicit buffered output assignments
   w_rdy <= w_rdy_internal;

END struct;
