-- VHDL Entity alien_game_lib.c6_b1_victory_heart.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-306-SPC)
--          at - 15:50:03  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b1_victory_heart IS
   PORT( 
      idx           : IN     std_logic_vector (1 DOWNTO 0)  := "00";
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"00FFFF";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00"
   );

-- Declarations

END c6_b1_victory_heart ;

--
-- VHDL Architecture alien_game_lib.c6_b1_victory_heart.tbl
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-306-SPC)
--          at - 15:50:03  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c6_b1_victory_heart IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = X"0000") THEN
         victory_x <= X"00";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0001") THEN
         victory_x <= X"00";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0002") THEN
         victory_x <= X"00";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0003") THEN
         victory_x <= X"01";
         victory_y <= X"02";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0004") THEN
         victory_x <= X"01";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0005") THEN
         victory_x <= X"01";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0006") THEN
         victory_x <= X"01";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0007") THEN
         victory_x <= X"01";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0008") THEN
         victory_x <= X"02";
         victory_y <= X"02";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0009") THEN
         victory_x <= X"02";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000A") THEN
         victory_x <= X"02";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000B") THEN
         victory_x <= X"02";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000C") THEN
         victory_x <= X"01";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000D") THEN
         victory_x <= X"01";
         victory_y <= X"40";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000E") THEN
         victory_x <= X"04";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"000F") THEN
         victory_x <= X"04";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0010") THEN
         victory_x <= X"04";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0020") THEN
         victory_x <= X"04";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0030") THEN
         victory_x <= X"04";
         victory_y <= X"40";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0040") THEN
         victory_x <= X"04";
         victory_y <= X"60";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0050") THEN
         victory_x <= X"08";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0060") THEN
         victory_x <= X"08";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0070") THEN
         victory_x <= X"08";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0080") THEN
         victory_x <= X"08";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"0090") THEN
         victory_x <= X"08";
         victory_y <= X"40";
         victory_color <= X"FF0000";
      ELSIF (idx = X"00A0") THEN
         victory_x <= X"08";
         victory_y <= X"60";
         victory_color <= X"FF0000";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
