-- VHDL Entity alien_game_lib.c6_b1_victory_line2.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 17:54:32  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b1_victory_line2 IS
   PORT( 
      idx           : IN     std_logic_vector (7 DOWNTO 0)  := X"00";
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"0000FF";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"00"
   );

-- Declarations

END c6_b1_victory_line2 ;

--
-- VHDL Architecture alien_game_lib.c6_b1_victory_line2.tbl
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 17:54:32  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c6_b1_victory_line2 IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = X"01") THEN
         victory_x <= X"01";
         victory_y <= X"02";
         victory_color <= X"0000FF";
      ELSIF (idx = X"02") THEN
         victory_x <= X"01";
         victory_y <= X"04";
         victory_color <= X"0000FF";
      ELSIF (idx = X"03") THEN
         victory_x <= X"01";
         victory_y <= X"08";
         victory_color <= X"0000FF";
      ELSIF (idx = X"04") THEN
         victory_x <= X"01";
         victory_y <= X"10";
         victory_color <= X"0000FF";
      ELSIF (idx = X"05") THEN
         victory_x <= X"01";
         victory_y <= X"20";
         victory_color <= X"0000FF";
      ELSIF (idx = X"06") THEN
         victory_x <= X"01";
         victory_y <= X"40";
         victory_color <= X"0000FF";
      ELSIF (idx = X"07") THEN
         victory_x <= X"04";
         victory_y <= X"02";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"08") THEN
         victory_x <= X"04";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"09") THEN
         victory_x <= X"04";
         victory_y <= X"08";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0A") THEN
         victory_x <= X"04";
         victory_y <= X"10";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0B") THEN
         victory_x <= X"04";
         victory_y <= X"20";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0C") THEN
         victory_x <= X"04";
         victory_y <= X"40";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0D") THEN
         victory_x <= X"10";
         victory_y <= X"02";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"0E") THEN
         victory_x <= X"10";
         victory_y <= X"04";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"0F") THEN
         victory_x <= X"10";
         victory_y <= X"08";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"10") THEN
         victory_x <= X"10";
         victory_y <= X"10";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"11") THEN
         victory_x <= X"10";
         victory_y <= X"20";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"12") THEN
         victory_x <= X"10";
         victory_y <= X"40";
         victory_color <= X"FF00FF";
      ELSIF (idx = X"13") THEN
         victory_x <= X"40";
         victory_y <= X"02";
         victory_color <= X"FF0000";
      ELSIF (idx = X"14") THEN
         victory_x <= X"40";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"15") THEN
         victory_x <= X"40";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"16") THEN
         victory_x <= X"40";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"17") THEN
         victory_x <= X"40";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"18") THEN
         victory_x <= X"40";
         victory_y <= X"40";
         victory_color <= X"FF0000";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
