-- VHDL Entity alien_game_lib.c6_b1_victory_top.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:37:20 24.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b1_victory_top IS
   PORT( 
      clk           : IN     std_logic;
      rst_n         : IN     std_logic;
      victory_color : OUT    std_logic_vector (23 DOWNTO 0);
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0);
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c6_b1_victory_top ;

--
-- VHDL Architecture alien_game_lib.c6_b1_victory_top.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 20:26:41  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_b1_victory_top IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout1       : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2       : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3       : std_logic_vector(7 DOWNTO 0);
   SIGNAL fout        : std_logic;
   SIGNAL idx_add_one : std_logic_vector(7 DOWNTO 0);
   SIGNAL idx_next    : std_logic_vector(7 DOWNTO 0);
   SIGNAL idx_now     : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c6_b1_victory_line2
   PORT (
      idx           : IN     std_logic_vector (7 DOWNTO 0) := X"00";
      victory_color : OUT    std_logic_vector (23 DOWNTO 0);
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0) := X"00";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0) := X"00"
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b1_victory_line2 USE ENTITY alien_game_lib.c6_b1_victory_line2;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'add_one' of 'add'
   add_onecombo_proc: PROCESS (idx_now, dout1)
   VARIABLE temp_din0 : std_logic_vector(8 DOWNTO 0);
   VARIABLE temp_din1 : std_logic_vector(8 DOWNTO 0);
   VARIABLE temp_sum : unsigned(8 DOWNTO 0);
   VARIABLE temp_carry : std_logic;
   BEGIN
      temp_din0 := '0' & idx_now;
      temp_din1 := '0' & dout1;
      temp_carry := '0';
      temp_sum := unsigned(temp_din0) + unsigned(temp_din1) + temp_carry;
      idx_add_one <= conv_std_logic_vector(temp_sum(7 DOWNTO 0),8);
   END PROCESS add_onecombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   idx_now <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= idx_next;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'at_last_idx' of 'comp'
   at_last_idxcombo_proc : PROCESS (idx_now, dout2)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(idx_now) = unsigned(dout2)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS at_last_idxcombo_proc;

   -- ModuleWare code(v1.12) for instance 'const_last_idx' of 'constval'
   dout2 <= "00011000";

   -- ModuleWare code(v1.12) for instance 'const_one' of 'constval'
   dout1 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'const_zero' of 'constval'
   dout3 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(idx_add_one, dout3, fout)
   BEGIN
      CASE fout IS
      WHEN '0' => idx_next <= idx_add_one;
      WHEN '1' => idx_next <= dout3;
      WHEN OTHERS => idx_next <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_0 : c6_b1_victory_line2
      PORT MAP (
         idx           => idx_now,
         victory_color => victory_color,
         victory_x     => victory_x,
         victory_y     => victory_y
      );

END struct;
