-- VHDL Entity alien_game_lib.c6_b2_register_single.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 14:33:38  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b2_register_single IS
   PORT( 
      clear     : IN     std_logic;
      clk       : IN     std_logic;
      pixel_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic;
      we        : IN     std_logic;
      pixel_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c6_b2_register_single ;

--
-- VHDL Architecture alien_game_lib.c6_b2_register_single.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 14:33:38  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c6_b2_register_single IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(23 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   pixel_out <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, dout)
   BEGIN
      IF (dout = '1') THEN
         mw_U_0reg_cval <= "000000000000000000000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (we = '1') THEN
            mw_U_0reg_cval <= pixel_in;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inv'
   dout1 <= NOT(rst_n);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   dout <= dout1 OR clear;

   -- Instance port mappings.

END struct;
