-- VHDL Entity alien_game_lib.c6_b2_register_matrix.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:59:11  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_b2_register_matrix IS
   PORT( 
      clear     : IN     std_logic;
      clk       : IN     std_logic;
      pixel_in  : IN     std_logic_vector (23 DOWNTO 0);
      rst_n     : IN     std_logic;
      we_col    : IN     std_logic;
      x_read    : IN     std_logic_vector (2 DOWNTO 0);
      x_write   : IN     std_logic_vector (2 DOWNTO 0);
      y_read    : IN     std_logic_vector (2 DOWNTO 0);
      y_write   : IN     std_logic_vector (2 DOWNTO 0);
      pixel_out : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c6_b2_register_matrix ;

--
-- VHDL Architecture alien_game_lib.c6_b2_register_matrix.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:59:11  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_b2_register_matrix IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout        : std_logic;
   SIGNAL dout1       : std_logic;
   SIGNAL dout2       : std_logic;
   SIGNAL dout3       : std_logic;
   SIGNAL dout4       : std_logic;
   SIGNAL dout5       : std_logic;
   SIGNAL dout6       : std_logic;
   SIGNAL dout7       : std_logic;
   SIGNAL pixel_out_0 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_3 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_4 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_5 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_6 : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out_7 : std_logic_vector(23 DOWNTO 0);
   SIGNAL we_0        : std_logic;
   SIGNAL we_1        : std_logic;
   SIGNAL we_2        : std_logic;
   SIGNAL we_3        : std_logic;
   SIGNAL we_4        : std_logic;
   SIGNAL we_5        : std_logic;
   SIGNAL we_6        : std_logic;
   SIGNAL we_7        : std_logic;


   -- Component Declarations
   COMPONENT c6_b2_register_row
   PORT (
      clear    : IN     std_logic ;
      clk      : IN     std_logic ;
      pixel_in : IN     std_logic_vector (23 DOWNTO 0);
      rst_n    : IN     std_logic ;
      we_row   : IN     std_logic ;
      x_read   : IN     std_logic_vector (2 DOWNTO 0);
      x_write  : IN     std_logic_vector (2 DOWNTO 0);
      row_out  : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b2_register_row USE ENTITY alien_game_lib.c6_b2_register_row;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   dout <= we_col AND we_0;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'and'
   dout1 <= we_col AND we_1;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'and'
   dout2 <= we_col AND we_2;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'and'
   dout3 <= we_col AND we_3;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout4 <= we_col AND we_4;

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   dout5 <= we_col AND we_5;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'and'
   dout6 <= we_col AND we_6;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   dout7 <= we_col AND we_7;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'decoder'
   we_0 <= NOT(y_write(2)) AND NOT(y_write(1)) AND NOT(y_write(0));
   we_1 <= NOT(y_write(2)) AND NOT(y_write(1)) AND y_write(0);
   we_2 <= NOT(y_write(2)) AND y_write(1) AND NOT(y_write(0));
   we_3 <= NOT(y_write(2)) AND y_write(1) AND y_write(0);
   we_4 <= y_write(2) AND NOT(y_write(1)) AND NOT(y_write(0));
   we_5 <= y_write(2) AND NOT(y_write(1)) AND y_write(0);
   we_6 <= y_write(2) AND y_write(1) AND NOT(y_write(0));
   we_7 <= y_write(2) AND y_write(1) AND y_write(0);

   -- ModuleWare code(v1.12) for instance 'U_18' of 'mux'
   u_18combo_proc: PROCESS(pixel_out_0, pixel_out_1, pixel_out_2, 
                           pixel_out_3, pixel_out_4, pixel_out_5, 
                           pixel_out_6, pixel_out_7, y_read)
   BEGIN
      CASE y_read IS
      WHEN "000" => pixel_out <= pixel_out_0;
      WHEN "001" => pixel_out <= pixel_out_1;
      WHEN "010" => pixel_out <= pixel_out_2;
      WHEN "011" => pixel_out <= pixel_out_3;
      WHEN "100" => pixel_out <= pixel_out_4;
      WHEN "101" => pixel_out <= pixel_out_5;
      WHEN "110" => pixel_out <= pixel_out_6;
      WHEN "111" => pixel_out <= pixel_out_7;
      WHEN OTHERS => pixel_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_18combo_proc;

   -- Instance port mappings.
   U_0 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_0
      );
   U_1 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout1,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_1
      );
   U_2 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout2,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_2
      );
   U_3 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout3,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_3
      );
   U_4 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout4,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_4
      );
   U_5 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout5,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_5
      );
   U_6 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout6,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_6
      );
   U_7 : c6_b2_register_row
      PORT MAP (
         clear    => clear,
         clk      => clk,
         pixel_in => pixel_in,
         rst_n    => rst_n,
         we_row   => dout7,
         x_read   => x_read,
         x_write  => x_write,
         row_out  => pixel_out_7
      );

END struct;
