-- VHDL Entity alien_game_lib.c6_t1_register_controller.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:26:06  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t1_register_controller IS
   PORT( 
      clk        : IN     std_logic;
      frame_done : IN     std_logic;
      rst        : IN     std_logic;
      clear_mem0 : OUT    std_logic;
      clear_mem1 : OUT    std_logic;
      w_rdy      : OUT    std_logic;
      wr_sel     : OUT    std_logic
   );

-- Declarations

END c6_t1_register_controller ;

--
-- VHDL Architecture alien_game_lib.c6_t1_register_controller.fsm
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:26:03  4.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c6_t1_register_controller IS

   TYPE STATE_TYPE IS (
      WRITE,
      SWAP
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= WRITE;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      frame_done
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN WRITE => 
            IF (frame_done = '1') THEN 
               next_state <= SWAP;
            ELSE
               next_state <= WRITE;
            END IF;
         WHEN SWAP => 
            IF (TRUE) THEN 
               next_state <= WRITE;
            ELSE
               next_state <= SWAP;
            END IF;
         WHEN OTHERS =>
            next_state <= WRITE;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state,
      wr_sel
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN WRITE => 
            w_rdy <= '1' ;
            clear_mem0 <= '0' ;
            clear_mem1 <= '0' ;
         WHEN SWAP => 
            w_rdy <= '0' ;
            wr_sel <= NOT wr_sel ;
            clear_mem0 <= wr_sel ;
            clear_mem1 <= NOT wr_sel ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
