-- VHDL Entity alien_game_lib.c6_t1_hit_detect.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:58:42 20.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t1_hit_detect IS
   PORT( 
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      hit            : OUT    std_logic
   );

-- Declarations

END c6_t1_hit_detect ;

--
-- VHDL Architecture alien_game_lib.c6_t1_hit_detect.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:58:42 20.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c6_t1_hit_detect IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout           : std_logic;
   SIGNAL fout           : std_logic;
   SIGNAL fout1          : std_logic;
   SIGNAL match_now      : std_logic;
   SIGNAL match_previous : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   match_previous <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= match_now;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'match_now' of 'and'
   match_now <= fout AND fout1;

   -- ModuleWare code(v1.12) for instance 'match_now1' of 'and'
   hit <= match_now AND dout;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'comp'
   u_1combo_proc : PROCESS (alien_y_coord, bullet_y_coord)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(alien_y_coord) = unsigned(bullet_y_coord)) THEN
         temp_lout := '1';
      END IF;
   fout1 <= temp_lout;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'comp'
   u_2combo_proc : PROCESS (alien_x_coord, bullet_x_coord)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(alien_x_coord) = unsigned(bullet_x_coord)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   dout <= NOT(match_previous);

   -- Instance port mappings.

END struct;
