-- VHDL Entity alien_game_lib.c7_b1_alien_hit_point.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:03:58  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_alien_hit_point IS
   PORT( 
      clk   : IN     std_logic;
      hit   : IN     std_logic;
      rst_n : IN     std_logic;
      hp    : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END c7_b1_alien_hit_point ;

--
-- VHDL Architecture alien_game_lib.c7_b1_alien_hit_point.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:03:58  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_b1_alien_hit_point IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic_vector(1 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL hp_internal : std_logic_vector (1 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(1 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'add'
   u_1combo_proc: PROCESS (hp_internal, dout)
   VARIABLE temp_din0 : std_logic_vector(2 DOWNTO 0);
   VARIABLE temp_din1 : std_logic_vector(2 DOWNTO 0);
   VARIABLE temp_sum : unsigned(2 DOWNTO 0);
   VARIABLE temp_carry : std_logic;
   BEGIN
      temp_din0 := '0' & hp_internal;
      temp_din1 := "00" & dout;
      temp_carry := '0';
      temp_sum := unsigned(temp_din0) + unsigned(temp_din1) + temp_carry;
      dout1 <= conv_std_logic_vector(temp_sum(1 DOWNTO 0),2);
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   hp_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_0reg_cval <= "00";
         ELSIF (hit = '1') THEN
            mw_U_0reg_cval <= dout1;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'const_one' of 'constval'
   dout <= '1';

   -- Instance port mappings.

   -- Implicit buffered output assignments
   hp <= hp_internal;

END struct;
