-- VHDL Entity alien_game_lib.c7_b1_alien_defeated_improved.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:01:01  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_alien_defeated_improved IS
   PORT( 
      clk            : IN     std_logic;
      hp             : IN     std_logic_vector (1 DOWNTO 0);
      rst_n          : IN     std_logic;
      alien_defeated : OUT    std_logic
   );

-- Declarations

END c7_b1_alien_defeated_improved ;

--
-- VHDL Architecture alien_game_lib.c7_b1_alien_defeated_improved.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:37:26  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_b1_alien_defeated_improved IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout1 : std_logic;
   SIGNAL fout  : std_logic;
   SIGNAL q     : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= dout1;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'comp'
   u_3combo_proc : PROCESS (hp, dout)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(hp) = unsigned(dout)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'target_points' of 'constval'
   dout <= "11";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   dout1 <= fout OR q;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'pbuf'
   u_2seq_proc: PROCESS (q)
   BEGIN
      IF (q ='1' ) THEN
         alien_defeated <= '1';
      ELSIF (q ='H' ) THEN
         alien_defeated <= '1';
      ELSIF (q ='0' ) THEN
         alien_defeated <= '0';
      ELSIF (q ='L' ) THEN
         alien_defeated <= '0';
      ELSIF (q ='U' ) THEN
         alien_defeated <= 'U';
      ELSIF (q ='X' ) THEN
         alien_defeated <= 'X';
      ELSIF (q ='Z' ) THEN
         alien_defeated <= 'X';
      END IF;
   END PROCESS u_2seq_proc;

   -- Instance port mappings.

END struct;
