-- VHDL Entity alien_game_lib.c7_b1_lose_cross.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:47:25  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_lose_cross IS
   PORT( 
      idx        : IN     std_logic_vector (7 DOWNTO 0);
      lose_color : OUT    std_logic_vector (23 DOWNTO 0) := X"FF0000";
      lose_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"04";
      lose_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"80"
   );

-- Declarations

END c7_b1_lose_cross ;

--
-- VHDL Architecture alien_game_lib.c7_b1_lose_cross.tbl
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:00:09  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c7_b1_lose_cross IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = X"01") THEN
         lose_x <= X"04";
         lose_y <= X"10";
         lose_color <= X"0000FF";
      ELSIF (idx = X"02") THEN
         lose_x <= X"08";
         lose_y <= X"08";
         lose_color <= X"0000FF";
      ELSIF (idx = X"03") THEN
         lose_x <= X"10";
         lose_y <= X"04";
         lose_color <= X"0000FF";
      ELSIF (idx = X"04") THEN
         lose_x <= X"08";
         lose_y <= X"20";
         lose_color <= X"0000FF";
      ELSIF (idx = X"05") THEN
         lose_x <= X"10";
         lose_y <= X"10";
         lose_color <= X"0000FF";
      ELSIF (idx = X"06") THEN
         lose_x <= X"20";
         lose_y <= X"08";
         lose_color <= X"0000FF";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
