-- VHDL Entity alien_game_lib.c7_b1_top_end.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:11:04  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_top_end IS
   PORT( 
      alien_defeated   : IN     std_logic;
      clk              : IN     std_logic;
      rst_n            : IN     std_logic;
      end_symbol_color : OUT    std_logic_vector (23 DOWNTO 0);
      end_symbol_x     : OUT    std_logic_vector (7 DOWNTO 0);
      end_symbol_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c7_b1_top_end ;

--
-- VHDL Architecture alien_game_lib.c7_b1_top_end.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:33:21  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c7_b1_top_end IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout          : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1         : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2         : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3         : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4         : std_logic_vector(7 DOWNTO 0);
   SIGNAL fout          : std_logic;
   SIGNAL idx_add_one   : std_logic_vector(7 DOWNTO 0);
   SIGNAL idx_next      : std_logic_vector(7 DOWNTO 0);
   SIGNAL idx_now       : std_logic_vector(7 DOWNTO 0);
   SIGNAL lose_color    : std_logic_vector(23 DOWNTO 0) := X"FF0000";
   SIGNAL lose_x        : std_logic_vector(7 DOWNTO 0)  := X"01";
   SIGNAL lose_y        : std_logic_vector(7 DOWNTO 0)  := X"01";
   SIGNAL victory_color : std_logic_vector(23 DOWNTO 0) := X"00FF00";
   SIGNAL victory_x     : std_logic_vector(7 DOWNTO 0)  := X"01";
   SIGNAL victory_y     : std_logic_vector(7 DOWNTO 0)  := X"01";


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic_vector(7 DOWNTO 0);

   -- Component Declarations
   COMPONENT c7_b1_lose_cross
   PORT (
      idx        : IN     std_logic_vector (7 DOWNTO 0);
      lose_color : OUT    std_logic_vector (23 DOWNTO 0) := X"FF0000";
      lose_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"04";
      lose_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"80"
   );
   END COMPONENT;
   COMPONENT c7_b1_victory_rainbow
   PORT (
      idx           : IN     std_logic_vector (7 DOWNTO 0);
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"00FF00";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"01";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"01"
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c7_b1_lose_cross USE ENTITY alien_game_lib.c7_b1_lose_cross;
   FOR ALL : c7_b1_victory_rainbow USE ENTITY alien_game_lib.c7_b1_victory_rainbow;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'add_one' of 'add'
   add_onecombo_proc: PROCESS (idx_now, dout1)
   VARIABLE temp_din0 : std_logic_vector(8 DOWNTO 0);
   VARIABLE temp_din1 : std_logic_vector(8 DOWNTO 0);
   VARIABLE temp_sum : unsigned(8 DOWNTO 0);
   VARIABLE temp_carry : std_logic;
   BEGIN
      temp_din0 := '0' & idx_now;
      temp_din1 := '0' & dout1;
      temp_carry := '0';
      temp_sum := unsigned(temp_din0) + unsigned(temp_din1) + temp_carry;
      idx_add_one <= conv_std_logic_vector(temp_sum(7 DOWNTO 0),8);
   END PROCESS add_onecombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   idx_now <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= idx_next;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'at_last_idx' of 'comp'
   at_last_idxcombo_proc : PROCESS (idx_now, dout4)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(idx_now) = unsigned(dout4)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS at_last_idxcombo_proc;

   -- ModuleWare code(v1.12) for instance 'const_one' of 'constval'
   dout1 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'const_zero' of 'constval'
   dout3 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'lose_last_idx' of 'constval'
   dout <= "00000110";

   -- ModuleWare code(v1.12) for instance 'victory_last_idx' of 'constval'
   dout2 <= "00101010";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(lose_x, victory_x, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => end_symbol_x <= lose_x;
      WHEN '1' => end_symbol_x <= victory_x;
      WHEN OTHERS => end_symbol_x <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(lose_y, victory_y, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => end_symbol_y <= lose_y;
      WHEN '1' => end_symbol_y <= victory_y;
      WHEN OTHERS => end_symbol_y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(lose_color, victory_color, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => end_symbol_color <= lose_color;
      WHEN '1' => end_symbol_color <= victory_color;
      WHEN OTHERS => end_symbol_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(idx_add_one, dout3, fout)
   BEGIN
      CASE fout IS
      WHEN '0' => idx_next <= idx_add_one;
      WHEN '1' => idx_next <= dout3;
      WHEN OTHERS => idx_next <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout, dout2, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => dout4 <= dout;
      WHEN '1' => dout4 <= dout2;
      WHEN OTHERS => dout4 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_7combo_proc;

   -- Instance port mappings.
   U_2 : c7_b1_lose_cross
      PORT MAP (
         idx        => idx_now,
         lose_color => lose_color,
         lose_x     => lose_x,
         lose_y     => lose_y
      );
   U_0 : c7_b1_victory_rainbow
      PORT MAP (
         idx           => idx_now,
         victory_color => victory_color,
         victory_x     => victory_x,
         victory_y     => victory_y
      );

END struct;
