-- VHDL Entity alien_game_lib.c7_b1_alien_color_improved.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 16:17:23  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_alien_color_improved IS
   PORT( 
      hp          : IN     std_logic_vector (1 DOWNTO 0);
      alien_color : OUT    std_logic_vector (23 DOWNTO 0)
   );

-- Declarations

END c7_b1_alien_color_improved ;

--
-- VHDL Architecture alien_game_lib.c7_b1_alien_color_improved.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 16:17:22  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_b1_alien_color_improved IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(23 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'C_Green' of 'constval'
   dout1 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'C_None' of 'constval'
   dout3 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'C_Red' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'C_Yellow' of 'constval'
   dout2 <= "000000001111111111111111";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout1, dout2, dout, dout3, hp)
   BEGIN
      CASE hp IS
      WHEN "00" => alien_color <= dout1;
      WHEN "01" => alien_color <= dout2;
      WHEN "10" => alien_color <= dout;
      WHEN "11" => alien_color <= dout3;
      WHEN OTHERS => alien_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
