-- VHDL Entity alien_game_lib.c7_b1_victory_rainbow.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:59:03  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_victory_rainbow IS
   PORT( 
      idx           : IN     std_logic_vector (7 DOWNTO 0);
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"0000FF";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"02";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"02"
   );

-- Declarations

END c7_b1_victory_rainbow ;

--
-- VHDL Architecture alien_game_lib.c7_b1_victory_rainbow.tbl
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:59:02  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c7_b1_victory_rainbow IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = X"01") THEN
         victory_x <= X"02";
         victory_y <= X"02";
         victory_color <= X"0000FF";
      ELSIF (idx = X"02") THEN
         victory_x <= X"02";
         victory_y <= X"04";
         victory_color <= X"0000FF";
      ELSIF (idx = X"03") THEN
         victory_x <= X"02";
         victory_y <= X"08";
         victory_color <= X"0000FF";
      ELSIF (idx = X"04") THEN
         victory_x <= X"02";
         victory_y <= X"10";
         victory_color <= X"0000FF";
      ELSIF (idx = X"05") THEN
         victory_x <= X"02";
         victory_y <= X"20";
         victory_color <= X"0000FF";
      ELSIF (idx = X"06") THEN
         victory_x <= X"02";
         victory_y <= X"40";
         victory_color <= X"0000FF";
      ELSIF (idx = X"07") THEN
         victory_x <= X"04";
         victory_y <= X"02";
         victory_color <= X"0007FF";
      ELSIF (idx = X"08") THEN
         victory_x <= X"04";
         victory_y <= X"04";
         victory_color <= X"0007FF";
      ELSIF (idx = X"09") THEN
         victory_x <= X"04";
         victory_y <= X"08";
         victory_color <= X"0007FF";
      ELSIF (idx = X"0A") THEN
         victory_x <= X"04";
         victory_y <= X"10";
         victory_color <= X"0007FF";
      ELSIF (idx = X"0B") THEN
         victory_x <= X"04";
         victory_y <= X"20";
         victory_color <= X"0007FF";
      ELSIF (idx = X"0C") THEN
         victory_x <= X"04";
         victory_y <= X"40";
         victory_color <= X"0007FF";
      ELSIF (idx = X"0D") THEN
         victory_x <= X"08";
         victory_y <= X"02";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0E") THEN
         victory_x <= X"08";
         victory_y <= X"04";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"0F") THEN
         victory_x <= X"08";
         victory_y <= X"08";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"10") THEN
         victory_x <= X"08";
         victory_y <= X"10";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"11") THEN
         victory_x <= X"08";
         victory_y <= X"20";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"12") THEN
         victory_x <= X"08";
         victory_y <= X"40";
         victory_color <= X"00FFFF";
      ELSIF (idx = X"13") THEN
         victory_x <= X"10";
         victory_y <= X"02";
         victory_color <= X"00FF00";
      ELSIF (idx = X"14") THEN
         victory_x <= X"10";
         victory_y <= X"04";
         victory_color <= X"00FF00";
      ELSIF (idx = X"15") THEN
         victory_x <= X"10";
         victory_y <= X"08";
         victory_color <= X"00FF00";
      ELSIF (idx = X"16") THEN
         victory_x <= X"10";
         victory_y <= X"10";
         victory_color <= X"00FF00";
      ELSIF (idx = X"17") THEN
         victory_x <= X"10";
         victory_y <= X"20";
         victory_color <= X"00FF00";
      ELSIF (idx = X"18") THEN
         victory_x <= X"10";
         victory_y <= X"40";
         victory_color <= X"00FF00";
      ELSIF (idx = X"19") THEN
         victory_x <= X"20";
         victory_y <= X"02";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1A") THEN
         victory_x <= X"20";
         victory_y <= X"04";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1B") THEN
         victory_x <= X"20";
         victory_y <= X"08";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1C") THEN
         victory_x <= X"20";
         victory_y <= X"10";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1D") THEN
         victory_x <= X"20";
         victory_y <= X"20";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1E") THEN
         victory_x <= X"20";
         victory_y <= X"40";
         victory_color <= X"FF0000";
      ELSIF (idx = X"1F") THEN
         victory_x <= X"40";
         victory_y <= X"02";
         victory_color <= X"62004B";
      ELSIF (idx = X"20") THEN
         victory_x <= X"40";
         victory_y <= X"04";
         victory_color <= X"62004B";
      ELSIF (idx = X"21") THEN
         victory_x <= X"40";
         victory_y <= X"08";
         victory_color <= X"62004B";
      ELSIF (idx = X"22") THEN
         victory_x <= X"40";
         victory_y <= X"10";
         victory_color <= X"62004B";
      ELSIF (idx = X"23") THEN
         victory_x <= X"40";
         victory_y <= X"20";
         victory_color <= X"62004B";
      ELSIF (idx = X"24") THEN
         victory_x <= X"40";
         victory_y <= X"40";
         victory_color <= X"62004B";
      ELSIF (idx = X"25") THEN
         victory_x <= X"80";
         victory_y <= X"02";
         victory_color <= X"FF008F";
      ELSIF (idx = X"26") THEN
         victory_x <= X"80";
         victory_y <= X"04";
         victory_color <= X"FF008F";
      ELSIF (idx = X"27") THEN
         victory_x <= X"80";
         victory_y <= X"08";
         victory_color <= X"FF008F";
      ELSIF (idx = X"28") THEN
         victory_x <= X"80";
         victory_y <= X"10";
         victory_color <= X"FF008F";
      ELSIF (idx = X"29") THEN
         victory_x <= X"80";
         victory_y <= X"20";
         victory_color <= X"FF008F";
      ELSIF (idx = X"2A") THEN
         victory_x <= X"80";
         victory_y <= X"40";
         victory_color <= X"FF008F";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
