-- VHDL Entity alien_game_lib.c7_b1_alien_y_improved.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:31:30  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_alien_y_improved IS
   PORT( 
      clk       : IN     std_logic;
      hit_edge  : IN     std_logic;
      rst_n     : IN     std_logic;
      alien_win : OUT    std_logic;
      alien_y   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c7_b1_alien_y_improved ;

--
-- VHDL Architecture alien_game_lib.c7_b1_alien_y_improved.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 11:31:30  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_b1_alien_y_improved IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL fout  : std_logic;
   SIGNAL q     : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL alien_y_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'fixshift'
   SIGNAL mw_U_0temp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   alien_y_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= "00000001";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout2;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   q <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_5reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= dout3;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'comp'
   u_3combo_proc : PROCESS (dout2, dout)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(dout2) = unsigned(dout)) THEN
         temp_lout := '1';
      END IF;
   fout <= temp_lout;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'lost_line' of 'constval'
   dout <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'fixshift'
   dout1 <= mw_U_0temp_dout;
   u_0combo_proc: PROCESS (alien_y_internal)
   BEGIN
      mw_U_0temp_dout <= (OTHERS => '0');
      mw_U_0temp_dout(7 DOWNTO 1) <= alien_y_internal(6 + 0 DOWNTO 0);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(alien_y_internal, dout1, hit_edge)
   BEGIN
      CASE hit_edge IS
      WHEN '0' => dout2 <= alien_y_internal;
      WHEN '1' => dout2 <= dout1;
      WHEN OTHERS => dout2 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   dout3 <= q OR fout;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'pbuf'
   u_6seq_proc: PROCESS (q)
   BEGIN
      IF (q ='1' ) THEN
         alien_win <= '1';
      ELSIF (q ='H' ) THEN
         alien_win <= '1';
      ELSIF (q ='0' ) THEN
         alien_win <= '0';
      ELSIF (q ='L' ) THEN
         alien_win <= '0';
      ELSIF (q ='U' ) THEN
         alien_win <= 'U';
      ELSIF (q ='X' ) THEN
         alien_win <= 'X';
      ELSIF (q ='Z' ) THEN
         alien_win <= 'X';
      END IF;
   END PROCESS u_6seq_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   alien_y <= alien_y_internal;

END struct;
