-- VHDL Entity alien_game_lib.c7_b1_victory_rainbow.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 10:52:16  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_victory_rainbow IS
   PORT( 
      idx           : IN     std_logic_vector (7 DOWNTO 0);
      victory_color : OUT    std_logic_vector (23 DOWNTO 0) := X"00FF00";
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0)  := X"01";
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)  := X"01"
   );

-- Declarations

END c7_b1_victory_rainbow ;

--
-- VHDL Architecture alien_game_lib.c7_b1_victory_rainbow.tbl
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 10:52:16  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c7_b1_victory_rainbow IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(idx)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (idx = X"01") THEN
         victory_x <= X"01";
         victory_y <= X"02";
         victory_color <= X"0000FF";
      ELSIF (idx = X"02") THEN
         victory_x <= X"01";
         victory_y <= X"04";
         victory_color <= X"0000FF";
      ELSIF (idx = X"03") THEN
         victory_x <= X"01";
         victory_y <= X"08";
         victory_color <= X"0000FF";
      ELSIF (idx = X"04") THEN
         victory_x <= X"01";
         victory_y <= X"10";
         victory_color <= X"0000FF";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
