-- VHDL Entity alien_game_lib.c7_b1_alien_defeated_improved.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:01:01  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_b1_alien_defeated_improved IS
   PORT( 
      clk            : IN     std_logic;
      hp             : IN     std_logic_vector (1 DOWNTO 0);
      rst_n          : IN     std_logic;
      alien_defeated : OUT    std_logic
   );

-- Declarations

END c7_b1_alien_defeated_improved ;

--
-- VHDL Architecture alien_game_lib.c7_b1_alien_defeated_improved.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:13:04  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_b1_alien_defeated_improved IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL def_d : std_logic;
   SIGNAL dout  : std_logic_vector(1 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   alien_defeated <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= def_d;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'comp'
   u_3combo_proc : PROCESS (hp, dout)
   VARIABLE temp_lout : std_logic;
   
   BEGIN
   temp_lout := '0';
      IF (unsigned(hp) = unsigned(dout)) THEN
         temp_lout := '1';
      END IF;
   def_d <= temp_lout;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'target_points' of 'constval'
   dout <= "11";

   -- Instance port mappings.

END struct;
