-- VHDL Entity alien_game_lib.c7_t1_alien_y.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:44:33  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_t1_alien_y IS
   PORT( 
      alien_defeated : IN     std_logic;
      alien_y        : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c7_t1_alien_y ;

--
-- VHDL Architecture alien_game_lib.c7_t1_alien_y.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:44:33  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_t1_alien_y IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'Y_TOP' of 'constval'
   dout <= "00000001";

   -- ModuleWare code(v1.12) for instance 'Y_ZERO' of 'constval'
   dout1 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout, dout1, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => alien_y <= dout;
      WHEN '1' => alien_y <= dout1;
      WHEN OTHERS => alien_y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.

END struct;
