-- VHDL Entity alien_game_lib.c7_t1_alien_x.symbol
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:45:52  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c7_t1_alien_x IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      dir_q          : IN     std_logic;
      enable         : IN     std_logic;
      rst_n          : IN     std_logic;
      alien_x        : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c7_t1_alien_x ;

--
-- VHDL Architecture alien_game_lib.c7_t1_alien_x.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 12:45:52  2.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c7_t1_alien_x IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL X_ls   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_next : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_rs   : std_logic_vector(7 DOWNTO 0);
   SIGNAL X_step : std_logic_vector(7 DOWNTO 0);
   SIGNAL din1   : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL alien_x_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'left_shifter' of 'fixshift'
   SIGNAL mw_left_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'right_shifter' of 'fixshift'
   SIGNAL mw_right_shiftertemp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   alien_x_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000010";
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (enable = '1') THEN
            mw_U_0reg_cval <= X_next;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'X_ZERO' of 'constval'
   din1 <= "00000000";

   -- ModuleWare code(v1.12) for instance 'left_shifter' of 'fixshift'
   X_ls <= mw_left_shiftertemp_dout;
   left_shiftercombo_proc: PROCESS (alien_x_internal)
   BEGIN
      mw_left_shiftertemp_dout <= (OTHERS => '0');
      mw_left_shiftertemp_dout(7 DOWNTO 1) <= alien_x_internal(6 + 0 DOWNTO 0);
   END PROCESS left_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'right_shifter' of 'fixshift'
   X_rs <= mw_right_shiftertemp_dout;
   right_shiftercombo_proc: PROCESS (alien_x_internal)
   BEGIN
      mw_right_shiftertemp_dout <= (OTHERS => '0');
      mw_right_shiftertemp_dout(6 DOWNTO 0) <= alien_x_internal(7 + 0 DOWNTO 1 + 0);
   END PROCESS right_shiftercombo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(X_ls, X_rs, dir_q)
   BEGIN
      CASE dir_q IS
      WHEN '0' => X_step <= X_ls;
      WHEN '1' => X_step <= X_rs;
      WHEN OTHERS => X_step <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'defeated_ctrl' of 'mux'
   defeated_ctrlcombo_proc: PROCESS(X_step, din1, alien_defeated)
   BEGIN
      CASE alien_defeated IS
      WHEN '0' => X_next <= X_step;
      WHEN '1' => X_next <= din1;
      WHEN OTHERS => X_next <= (OTHERS => 'X');
      END CASE;
   END PROCESS defeated_ctrlcombo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   alien_x <= alien_x_internal;

END struct;
