-- VHDL Entity tb_lib.pixel_io_tester.symbol
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:28:20 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY pixel_io_tester IS
   PORT( 
      color : IN     std_logic_vector (23 DOWNTO 0);
      x     : IN     std_logic_vector (7 DOWNTO 0);
      y     : IN     std_logic_vector (7 DOWNTO 0);
      btn   : OUT    std_logic_vector (3 DOWNTO 0);
      sw0   : OUT    std_logic
   );

-- Declarations

END pixel_io_tester ;

--
-- VHDL Architecture tb_lib.pixel_io_tester.struct
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:28:21 23.01.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF pixel_io_tester IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- Instance port mappings.

END struct;
