-- VHDL Entity tb_lib.tb_bullet.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-308-SPC)
--          at - 13:40:19 05/31/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_bullet IS
-- Declarations

END tb_bullet ;

--
-- VHDL Architecture tb_lib.tb_bullet.struct
--
-- Created:
--          by - btjogr.UNKNOWN (HTC219-308-SPC)
--          at - 13:22:11  4.02.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_bullet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Gun_x_coord    : std_logic_vector(7 DOWNTO 0);
   SIGNAL btn            : std_logic_vector(3 DOWNTO 0);
   SIGNAL bullet_colour  : std_logic_vector(23 DOWNTO 0);
   SIGNAL bullet_x       : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_x_coord : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_y       : std_logic_vector(7 DOWNTO 0);
   SIGNAL bullet_y_coord : std_logic_vector(7 DOWNTO 0);
   SIGNAL clk            : std_logic;
   SIGNAL color          : std_logic_vector(23 DOWNTO 0);
   SIGNAL en             : std_logic;
   SIGNAL rst_n          : std_logic;


   -- Component Declarations
   COMPONENT c4_b1_bullet
   PORT (
      Gun_x_coord    : IN     std_logic_vector (7 DOWNTO 0);
      btn            : IN     std_logic_vector (3 DOWNTO 0);
      clk            : IN     std_logic ;
      enable         : IN     std_logic ;
      rst_n          : IN     std_logic ;
      bullet_x_coord : OUT    std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : OUT    std_logic_vector (7 DOWNTO 0);
      color          : OUT    std_logic_vector (23 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT bullet_test_block
   PORT (
      bullet_colour : IN     std_logic_vector (23 DOWNTO 0);
      bullet_x      : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y      : IN     std_logic_vector (7 DOWNTO 0);
      btn           : OUT    std_logic_vector (3 DOWNTO 0);
      clk           : OUT    std_logic;
      en            : OUT    std_logic;
      gun_x         : OUT    std_logic_vector (7 DOWNTO 0);
      rst_n         : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : bullet_test_block USE ENTITY tb_lib.bullet_test_block;
   FOR ALL : c4_b1_bullet USE ENTITY alien_game_lib.c4_b1_bullet;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : c4_b1_bullet
      PORT MAP (
         Gun_x_coord    => Gun_x_coord,
         btn            => btn,
         clk            => clk,
         enable         => en,
         rst_n          => rst_n,
         bullet_x_coord => bullet_x_coord,
         bullet_y_coord => bullet_y_coord,
         color          => color
      );
   U_0 : bullet_test_block
      PORT MAP (
         gun_x         => Gun_x_coord,
         clk           => clk,
         rst_n         => rst_n,
         btn           => btn,
         en            => en,
         bullet_x      => bullet_x,
         bullet_y      => bullet_y,
         bullet_colour => bullet_colour
      );

END struct;
