-- VHDL Entity tb_lib.tb_register_64.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-307-SPC)
--          at - 16:33:24 06/04/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_register_64 IS
-- Declarations

END tb_register_64 ;

--
-- VHDL Architecture tb_lib.tb_register_64.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 15:30:49  6.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_register_64 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk       : std_logic;
   SIGNAL pixd      : std_logic_vector(23 DOWNTO 0);
   SIGNAL pixel_out : std_logic_vector(23 DOWNTO 0);
   SIGNAL rst_n     : std_logic;
   SIGNAL w_done    : std_logic;
   SIGNAL w_rdy     : std_logic;
   SIGNAL write     : std_logic;
   SIGNAL x_read    : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_write   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_read    : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_write   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c6_b2_register_bank
   PORT (
      clk        : IN     std_logic ;
      frame_done : IN     std_logic ;
      pixel_in   : IN     std_logic_vector (23 DOWNTO 0);
      rst_n      : IN     std_logic ;
      write      : IN     std_logic ;
      x_read     : IN     std_logic_vector (7 DOWNTO 0);
      x_write    : IN     std_logic_vector (7 DOWNTO 0);
      y_read     : IN     std_logic_vector (7 DOWNTO 0);
      y_write    : IN     std_logic_vector (7 DOWNTO 0);
      pixel_out  : OUT    std_logic_vector (23 DOWNTO 0);
      w_rdy      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT register_tester
   PORT (
      pixd_from_duv : IN     std_logic_vector (23 DOWNTO 0);
      w_ready       : IN     std_logic ;
      clk           : OUT    std_logic ;
      pixd          : OUT    std_logic_vector (23 DOWNTO 0);
      rst_n         : OUT    std_logic ;
      w_done        : OUT    std_logic ;
      write         : OUT    std_logic ;
      x_read        : OUT    std_logic_vector (7 DOWNTO 0);
      x_write       : OUT    std_logic_vector (7 DOWNTO 0);
      y_read        : OUT    std_logic_vector (7 DOWNTO 0);
      y_write       : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b2_register_bank USE ENTITY alien_game_lib.c6_b2_register_bank;
   FOR ALL : register_tester USE ENTITY tb_lib.register_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : c6_b2_register_bank
      PORT MAP (
         clk        => clk,
         frame_done => w_done,
         pixel_in   => pixd,
         rst_n      => rst_n,
         write      => write,
         x_read     => x_read,
         x_write    => y_read,
         y_read     => x_write,
         y_write    => y_write,
         pixel_out  => pixel_out,
         w_rdy      => w_rdy
      );
   U_0 : register_tester
      PORT MAP (
         pixd_from_duv => pixel_out,
         w_ready       => w_rdy,
         clk           => clk,
         pixd          => pixd,
         rst_n         => rst_n,
         w_done        => w_done,
         write         => write,
         x_read        => x_read,
         x_write       => x_write,
         y_read        => y_read,
         y_write       => y_write
      );

END struct;
