-- VHDL Entity tb_lib.tb_victory.symbol
--
-- Created:
--          by - kayra.UNKNOWN (HTC219-307-SPC)
--          at - 16:21:43 06/04/18
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY tb_victory IS
-- Declarations

END tb_victory ;

--
-- VHDL Architecture tb_lib.tb_victory.struct
--
-- Created:
--          by - ptjiya.UNKNOWN (HTC219-307-SPC)
--          at - 09:47:37  5.03.2026
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;
LIBRARY tb_lib;

ARCHITECTURE struct OF tb_victory IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk           : std_logic;
   SIGNAL pixel_amount  : std_logic_vector(5 DOWNTO 0);
   SIGNAL rst_n         : std_logic;
   SIGNAL victory_color : std_logic_vector(23 DOWNTO 0);
   SIGNAL victory_x     : std_logic_vector(7 DOWNTO 0);
   SIGNAL victory_y     : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c6_b1_victory_top_static
   PORT (
      clk           : IN     std_logic ;
      rst_n         : IN     std_logic ;
      victory_color : OUT    std_logic_vector (23 DOWNTO 0);
      victory_x     : OUT    std_logic_vector (7 DOWNTO 0);
      victory_y     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT victory_text_test_block
   PORT (
      color        : IN     std_logic_vector (23 DOWNTO 0);
      pixel_amount : IN     std_logic_vector (5 DOWNTO 0);
      x_data       : IN     std_logic_vector (7 DOWNTO 0);
      y_data       : IN     std_logic_vector (7 DOWNTO 0);
      clk          : OUT    std_logic;
      rst_n        : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_b1_victory_top_static USE ENTITY alien_game_lib.c6_b1_victory_top_static;
   FOR ALL : victory_text_test_block USE ENTITY tb_lib.victory_text_test_block;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'pixel_amount' of 'constval'
   pixel_amount <= "101000";

   -- Instance port mappings.
   U_1 : c6_b1_victory_top_static
      PORT MAP (
         clk           => clk,
         rst_n         => rst_n,
         victory_color => victory_color,
         victory_x     => victory_x,
         victory_y     => victory_y
      );
   U_0 : victory_text_test_block
      PORT MAP (
         clk          => clk,
         rst_n        => rst_n,
         color        => victory_color,
         x_data       => victory_x,
         y_data       => victory_y,
         pixel_amount => pixel_amount
      );

END struct;
